### ISSUE TITLE
Cannot pay invoice: TemporaryChannelFailure

### ISSUE THREAD

**Issue by baryluk** [lightningnetwork/lnd#1242]
### Background

WARNING: I just started experimenting with lnd, and I do not know much about fee policies, routing, htlc, time locks, etc.

I got something out of the hodlmonkey.com and I am trying to pay an invoice using lnd.

### Your environment

* version of `lnd`: `0.4.1-beta` (precompiled)
* which operating system (`uname -a` on *Nix): Linux, amd64
* version of `btcd`, `bitcoind`, or other backend: bitcoind master (~2018-05-12, cb9bbf77726a00c69a798ac818abda8281f61b43 )

### Steps to reproduce

I got my bitcoind txindexed few days ago, and then I started lnd. I have enabled autopilot. Then I created a new address and funded it. In response to that lnd created just one big channel with 60% of what I deposited. Despite me asking for up to 5 channels. So next day I created another address and deposited some more BTC. lnd responded and created 3 more channels of varying capacity. All good. Now I do have 4 channels. 3 of them with capacity over 600000 sat.

I made a checkout at hodlmonkey.com, for a value of about 450000 sat. I got a encoded payment, and I am trying to pay using my lnd:

```text
$ ./lncli sendpayment --pay_req 'lnbc444....32'
{
	"payment_error": "unable to route payment to destination: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc420214e10)({\n Signature: (lnwire.Sig) (len=64 cap=64) {\n  00000000  01 .......  },\n ChainHash: (chainhash.Hash) (len=32 cap=32) 00000019xxx1d,\n ShortChannelID: (lnwire.ShortChannelID) 7:1xx4:1xx4,\n Timestamp: (uint32) 23yyy,\n Flags: (lnwire.ChanUpdateFlag) 3013,\n TimeLockDelta: (uint16) 1,\n HtlcMinimumMsat: (lnwire.MilliSatoshi) 3940649673949184 mSAT,\n BaseFee: (uint32) 65536000,\n FeeRate: (uint32) 65536000\n})\n)",
	"payment_preimage": "",
	"payment_route": null
}
```

```text
2018-05-13 01:19:52.618 [ERR] CRTR: Attempt to send payment 05xxx30 failed: TemporaryChannelFailure
2018-05-13 01:19:54.019 [ERR] CRTR: Attempt to send payment 05xxx30 failed: TemporaryChannelFailure
2018-05-13 01:19:56.639 [ERR] CRTR: Attempt to send payment 05xxx30 failed: TemporaryChannelFailure
2018-05-13 01:19:56.773 [INF] HSWC: Sent 0 satoshis received 0 satoshis in the last 10 seconds (0.6 tx/sec)
2018-05-13 01:19:57.564 [ERR] CRTR: Attempt to send payment 05xxx30 failed: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc4238c9950)({
 Signature: (lnwire.Sig) (len=64 cap=64) {
  00000000  01 .....
 },
 ChainHash: (chainhash.Hash) (len=32 cap=32) 00000019xxxxxxxxx1d,
 ShortChannelID: (lnwire.ShortChannelID) 7:1xxx4:1xx4,
 Timestamp: (uint32) 23yyy,
 Flags: (lnwire.ChanUpdateFlag) 3013,
 TimeLockDelta: (uint16) 1,
 HtlcMinimumMsat: (lnwire.MilliSatoshi) 3940649673949184 mSAT,
 BaseFee: (uint32) 65536000,
 FeeRate: (uint32) 65536000
})
)
```

```text
$ ./lncli decodepayreq 'lnbc44....d32'
{
    "destination": "039376f846cb4e137f3474baa7fbe74ec627745c7d5c54935b99fbb1b60a62c9b3",
    "payment_hash": "05xxx30",
    "num_satoshis": "4xyzxyz",
    "timestamp": "1526abcdef",
    "expiry": "3600",
    "description": "Order key: https://hodlmonkey.com/checkout/order-received/12345/?key=wc_order_abcdefg",
    "description_hash": "",
    "fallback_addr": "",
    "cltv_expiry": "144"
}
```

Yet, when I ask for a potential routes to this destination with the same amount:

```text
$ ./lncli queryroutes 039376f846cb4e137f3474baa7fbe74ec627745c7d5c54935b99fbb1b60a62c9b3 450000
{
    "routes": [
        {
            "total_time_lock": 522xyz,
            "total_fees": "2",
            "total_amt": "450002",
            "hops": [
                {
                    "chan_id": "57xxx",
                    "chan_capacity": "59xxxx",
                    "amt_to_forward": "450001",
                    "fee": "1",
                    "expiry": 522xyz
                },
                {
                    "chan_id": "57xxx",
                    "chan_capacity": "1xxxxxx",
                    "amt_to_forward": "450000",
                    "fee": "1",
                    "expiry": 522xyz
                },
                {
                    "chan_id": "57xxx",
                    "chan_capacity": "30xxxxxx",
                    "amt_to_forward": "450000",
                    "fee": "0",
                    "expiry": 522xyz
                }
            ]
        },
...
```

I got about 11 potential routes, shortest having total_fees of 2 sat and 3 hopes total.

```text
$ ./lncli listpayments
{
    "payments": [
    ]
}
```

Either it is a bug in lnd, or one of the nodes on the path is offline / not cooperating, in which case lnd should try another path, or there is not enough capacity in some channels, in which case lnd should not reported them in `queryroutes`, or it is simply a bug in lnd, which should be fixed, or it is intended result, in which case error message should be much clear what is going on and recommend workaround actions.

Thanks.

PS. I got the same error when using `payinvoice`, even if I set `--amt X` to some sane value, like `--amt 100`, or didn't pass it at all. (Not sure if this is to override amount in the invoice request, or to set maximal amount of lightning channel fees allowed to fulfill invoice).

**Comment by Roasbeef** [comment]
`TemporaryChannelFailure` is protocol level error. It means that along an HTLC route, a channel didn't have enough available bandwidth to carry the HTLC. The error returned is simply one of the _last_ errors we encounter. For example, if hodlmoney doesn't have sufficient inbound payment bandwidth, then you won't be able to pay them no matter how many paths are shown. The `queryroutes` RPC just looks at static graph information, so for example if all nodes are offline, then that'll still show a set of _eligible_ routes. 

I'd also recommend you use the latest master version, as a number of bugs have been fixed over the past week weeks. We'll be releasing `0.4.2` in a few days. 

> I got the same error when using payinvoice, even if I set --amt X 

If the invoice has a payment amount specified, then you can't override it atm.

**Comment by Roasbeef** [comment]
Also in the future may be worth searching the set of prior closed issues before creating a new one, thanks.

**Comment by baryluk** [comment]
I did check all previous issues, including the closed one, and I did find some mentioning TemporaryChannelFailure, but none was really similar to this one in my opinion.

I still think that the error message could be improved anyhow.

**Comment by baryluk** [comment]
Updated to current master version (2018-05-13 02:20 CEST) `"version": "0.4.1-beta commit=28b12116e42c83149b6c6b93b70d669a0702bd2d"`, still the same error and error message.

Is it possible to simulate routing or debug routing somehow more, do a dry run of payinvoice, and see the possible paths examined, and path chosen for execution, or if it fails possible fallback paths, or something?

I understand it might be hard to get more information than `unable to route payment to destination` , but maybe hint like what was the potential capacity to destination amount the shortest route, and route with highest potential capacity would be very useful. I.e. if I got something like this instead: `unable to route payment to destination: path of highest capacity xyz sat with 6 hopes, maximal capacity shortest path of xyz sat with 2 hops`, it would be so much more useful.

**Comment by Roasbeef** [comment]
> Is it possible to simulate routing or debug routing somehow more, do a dry run of payinvoice, and see the possible paths examined, and path chosen for execution, or if it fails possible fallback paths, or something?

If you use trace logging, you'll see the entire process in detail. 

Sure the error messages can be improved, how about we close this, then create a new more targetted issue?

**Comment by kikoncuo** [comment]
Testing with eclair and lnd

1. Both open a channel with the same node
2. A different user pays two invoice, 10 cents to eclair and 10 to LND
3. In less than a minute, both nodes try to send back 5 cents
4. LND can't find a path tx fails, Eclair can

How can I give a better report of this behaviour?

**Comment by Roasbeef** [comment]
Channels have a reserve, so you may not be able to send again, until you're
above that reserve even if you've received money.
