### ISSUE TITLE
Crash on startup, CNCT and SRVR reporting "bad-txns-vout-empty"

### ISSUE THREAD

**Issue by willezgo** [lightningnetwork/lnd#1306]
### Background

LND was working fine until I did a graceful reboot of the server and started getting these errors on LND's startup. After displaying the error, LND crashes.

```
2018-05-31 07:44:27.133 [INF] CNCT: ChannelArbitrator(0fae5dcc5ca92ea0b2a7eecdd2b6355be9810a44f336d0c052c4ecf4d482b7bd:0): starting state=StateBroadcastCommit
2018-05-31 07:44:27.136 [TRC] CNCT: ChannelArbitrator(0fae5dcc5ca92ea0b2a7eecdd2b6355be9810a44f336d0c052c4ecf4d482b7bd:0): attempting state step with trigger=chainTrigger from state=StateBroadcastCommit
2018-05-31 07:44:27.136 [INF] CNCT: ChannelArbitrator(0fae5dcc5ca92ea0b2a7eecdd2b6355be9810a44f336d0c052c4ecf4d482b7bd:0): force closing chan
2018-05-31 07:44:27.195 [DBG] LNWL: ChannelPoint(0fae5dcc5ca92ea0b2a7eecdd2b6355be9810a44f336d0c052c4ecf4d482b7bd:0), starting local commitment: (*lnwallet.commitment)(0xc4206a6000)({
 height: (uint64) 1,
 isOurs: (bool) true,
 ourMessageIndex: (uint64) 0,
 theirMessageIndex: (uint64) 0,
 ourHtlcIndex: (uint64) 0,
 theirHtlcIndex: (uint64) 0,
 txn: (*wire.MsgTx)(0xc4200c5800)({
  Version: (int32) 2,
  TxIn: ([]*wire.TxIn) (len=1 cap=1) {
   (*wire.TxIn)(0xc420330de0)({
    PreviousOutPoint: (wire.OutPoint) 0fae5dcc5ca92ea0b2a7eecdd2b6355be9810a44f336d0c052c4ecf4d482b7bd:0,
    SignatureScript: ([]uint8) {
    },
    Witness: (wire.TxWitness) <nil>,
    Sequence: (uint32) 2148093020
   })
  },
  TxOut: ([]*wire.TxOut) {
  },
  LockTime: (uint32) 548200124
 }),
 sig: ([]uint8) (len=70 cap=70) {
  00000000  30 44 02 20 7f 71 13 f0  72 31 bd fc ba 4e 3f e2  |0D. .q..r1...N?.|
  00000010  a0 ad e3 75 c6 00 b9 7e  15 2e 86 84 4c 11 10 c4  |...u...~....L...|
  00000020  ae 87 c1 f0 02 20 2e 54  61 e7 2b e8 db 23 a1 53  |..... .Ta.+..#.S|
  00000030  99 23 7f 8f d2 67 b2 26  9c 8a f1 7d 6b df a2 af  |.#...g.&...}k...|
  00000040  cf ef 9e 3f ed 1e                                 |...?..|
 },
 ourBalance: (lnwire.MilliSatoshi) 0 mSAT,
 theirBalance: (lnwire.MilliSatoshi) 19000 mSAT,
 fee: (btcutil.Amount) 0.00001081 BTC,
 feePerKw: (lnwallet.SatPerKWeight) 1494,
 dustLimit: (btcutil.Amount) 0.00000573 BTC,
 outgoingHTLCs: ([]lnwallet.PaymentDescriptor) <nil>,
 incomingHTLCs: ([]lnwallet.PaymentDescriptor) <nil>,
 outgoingHTLCIndex: (map[int32]*lnwallet.PaymentDescriptor) {
 },
 incomingHTLCIndex: (map[int32]*lnwallet.PaymentDescriptor) {
 }
})

2018-05-31 07:44:27.198 [DBG] LNWL: ChannelPoint(0fae5dcc5ca92ea0b2a7eecdd2b6355be9810a44f336d0c052c4ecf4d482b7bd:0), starting remote commitment: (*lnwallet.commitment)(0xc4206a6240)({
 height: (uint64) 1,
 isOurs: (bool) false,
 ourMessageIndex: (uint64) 0,
 theirMessageIndex: (uint64) 0,
 ourHtlcIndex: (uint64) 0,
 theirHtlcIndex: (uint64) 0,
 txn: (*wire.MsgTx)(0xc4200c5840)({
  Version: (int32) 2,
  TxIn: ([]*wire.TxIn) (len=1 cap=1) {
   (*wire.TxIn)(0xc420330e40)({
    PreviousOutPoint: (wire.OutPoint) 0fae5dcc5ca92ea0b2a7eecdd2b6355be9810a44f336d0c052c4ecf4d482b7bd:0,
    SignatureScript: ([]uint8) {
    },
    Witness: (wire.TxWitness) <nil>,
    Sequence: (uint32) 2148093020
   })
  },
  TxOut: ([]*wire.TxOut) {
  },
  LockTime: (uint32) 548200124
 }),
 sig: ([]uint8) {
 },
 ourBalance: (lnwire.MilliSatoshi) 0 mSAT,
 theirBalance: (lnwire.MilliSatoshi) 19000 mSAT,
 fee: (btcutil.Amount) 0.00001081 BTC,
 feePerKw: (lnwallet.SatPerKWeight) 1494,
 dustLimit: (btcutil.Amount) 0.00000546 BTC,
 outgoingHTLCs: ([]lnwallet.PaymentDescriptor) <nil>,
 incomingHTLCs: ([]lnwallet.PaymentDescriptor) <nil>,
 outgoingHTLCIndex: (map[int32]*lnwallet.PaymentDescriptor) {
 },
 incomingHTLCIndex: (map[int32]*lnwallet.PaymentDescriptor) {
 }
})

2018-05-31 07:44:27.198 [INF] HSWC: Removing channel link with ChannelID(bdb782d4f4ecc452c0d036f3440a81e95b35b6d2cdeea7b2a02ea95ccc5dae0f)
2018-05-31 07:44:27.199 [ERR] CNCT: unable to mark link inactive: channel link not found
2018-05-31 07:44:27.201 [INF] CNCT: Broadcasting force close transaction, ChannelPoint(0fae5dcc5ca92ea0b2a7eecdd2b6355be9810a44f336d0c052c4ecf4d482b7bd:0): (*wire.MsgTx)(0xc4200c5800)({
 Version: (int32) 2,
 TxIn: ([]*wire.TxIn) (len=1 cap=1) {
  (*wire.TxIn)(0xc420330de0)({
   PreviousOutPoint: (wire.OutPoint) 0fae5dcc5ca92ea0b2a7eecdd2b6355be9810a44f336d0c052c4ecf4d482b7bd:0,
   SignatureScript: ([]uint8) {
   },
   Witness: (wire.TxWitness) (len=4 cap=4) {
    ([]uint8) <nil>,
    ([]uint8) (len=71 cap=144) {
     00000000  30 44 02 20 7f 71 13 f0  72 31 bd fc ba 4e 3f e2  |0D. .q..r1...N?.|
     00000010  a0 ad e3 75 c6 00 b9 7e  15 2e 86 84 4c 11 10 c4  |...u...~....L...|
     00000020  ae 87 c1 f0 02 20 2e 54  61 e7 2b e8 db 23 a1 53  |..... .Ta.+..#.S|
     00000030  99 23 7f 8f d2 67 b2 26  9c 8a f1 7d 6b df a2 af  |.#...g.&...}k...|
     00000040  cf ef 9e 3f ed 1e 01                              |...?...|
    },
    ([]uint8) (len=72 cap=144) {
     00000000  30 45 02 21 00 c2 06 1f  eb d7 30 bb d3 b5 10 9b  |0E.!......0.....|
     00000010  27 2b 29 cf 54 30 4c ef  db a0 7c b0 57 c2 87 99  |'+).T0L...|.W...|
     00000020  0c a8 c1 83 81 02 20 0a  5d 30 fd 18 eb 6a 4e a4  |...... .]0...jN.|
     00000030  08 26 4f 41 96 21 54 e5  91 47 d6 b7 65 8b 29 4a  |.&OA.!T..G..e.)J|
     00000040  fe 3a 1f 45 da c9 7e 01                           |.:.E..~.|
    },
    ([]uint8) (len=71 cap=500) {
     00000000  52 21 02 c1 ce fd 79 99  2f ac af 20 e3 47 fc da  |R!....y./.. .G..|
     00000010  e3 c4 07 45 cf e9 6b 8d  ef b3 b8 c9 94 45 3d 26  |...E..k......E=&|
     00000020  76 8d eb 21 02 d4 db 80  c2 f2 9d 88 43 0d 25 6f  |v..!........C.%o|
     00000030  41 29 c9 fc 88 8d b5 c7  3a 72 a6 f8 ce 22 82 ce  |A)......:r..."..|
     00000040  b4 bd 22 9b 0c 52 ae                              |.."..R.|
    }
   },
   Sequence: (uint32) 2148093020
  })
 },
 TxOut: ([]*wire.TxOut) {
 },
 LockTime: (uint32) 548200124
})

2018-05-31 07:44:27.212 [ERR] CNCT: ChannelArbitrator(0fae5dcc5ca92ea0b2a7eecdd2b6355be9810a44f336d0c052c4ecf4d482b7bd:0): unable to broadcast close tx: -26: 16: bad-txns-vout-empty
2018-05-31 07:44:27.212 [ERR] CNCT: unable to advance state: -26: 16: bad-txns-vout-empty
2018-05-31 07:44:27.212 [ERR] SRVR: unable to start server: -26: 16: bad-txns-vout-empty

```

### Your environment

* LND 0.4.2 release 
* `Linux b0900f03bc92 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux`
* bitcoind 0.16.0
* runs in Docker container

### Steps to reproduce

I'm unsure, but looking at the logs here's probably how it went (to be confirmed):

- Bob opens a channel to Alice with very small balance on their side (19000 mSAT)
- Alice reboots her node
- error happens on startup

### Expected behaviour

LND gracefully prints an error without crashing and forgets about the dust in the channel.

### Actual behaviour

LND generates a transaction with no output and crashes because it cannot broadcast it.

**Comment by halseth** [comment]
This is really a dupe of #1118, but I agree that LND shouldn't crash encountering these dust channels.

**Comment by michael1011** [comment]
I have the exact same issue. Is there a temporary workaround for this?

**Comment by willezgo** [comment]
Thanks @halseth for the info!

@michael1011, by digging into #1118, I've seen Roasbeef suggested a patch here: https://github.com/lightningnetwork/lnd/issues/975#issuecomment-377613760

I checked out the latest release https://github.com/lightningnetwork/lnd/commit/7cf5ebe2650b6798182e10be198c7ffc1f1d6e19 and applied the change which is now located exactly on this line: https://github.com/lightningnetwork/lnd/blob/7cf5ebe2650b6798182e10be198c7ffc1f1d6e19/contractcourt/chain_arbitrator.go#L458

Just changing this line to a "continue", and recompiling fixed the problem for me.

**Comment by Roasbeef** [comment]
Yep if you apply that patch, then you'll be able to boot again. Closing at `0.4.2` has measures to ensure that `lnd` will no longer get into a state like this. It was likely the case that you entered this state with a prior release of `lnd`.

**Comment by pinheadmz** [comment]
@Roasbeef after applying the patch I get a new error in the log. I encountered the `bad-txns-vout-empty` after a crash, dunno maybe database got corrupted. Here's my version:
`LTND: Version 0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19`

and the new error after following that patch described above:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45d2d0]

goroutine 1 [running]:
github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).stateStep(0x13373600, 0x80e82, 0x0, 0x136125a0, 0x3, 0x3, 0x13351c40)
    /home/pi/gocode/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:443 +0xd0
github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).advanceState(0x13373600, 0x80e82, 0x80e00, 0x0, 0x0, 0x2, 0x0, 0x0)
    /home/pi/gocode/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:651 +0x138
github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).Start(0x13373600, 0x0, 0x0)
    /home/pi/gocode/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:248 +0x274
github.com/lightningnetwork/lnd/contractcourt.(*ChainArbitrator).Start(0x1331e280, 0x0, 0x0)
    /home/pi/gocode/src/github.com/lightningnetwork/lnd/contractcourt/chain_arbitrator.go:457 +0x730
main.(*server).Start(0x133981a0, 0x90167a, 0x2e)
    /home/pi/gocode/src/github.com/lightningnetwork/lnd/server.go:580 +0xd8
main.lndMain(0x0, 0x0)
    /home/pi/gocode/src/github.com/lightningnetwork/lnd/lnd.go:610 +0x15b4
main.main()
    /home/pi/gocode/src/github.com/lightningnetwork/lnd/lnd.go:651 +0x14
```
any thoughts on recovery? thanks

**Comment by Roasbeef** [comment]
You were initially running on a prior commit before 0.4.2 when you hit this? Well as in you may have been running on a prior one, you ran into this issue (which was fixed see https://github.com/lightningnetwork/lnd/issues/1247), but then updated and encountered this? 

If you basically insert a "continue" in that loop in the `Start()` method, then you should be able to progress past this.

**Comment by pinheadmz** [comment]
I was running `lnd version 0.4.1-beta commit=6fa93a78c18180a3bc77116b749b3c5e279d5a33` until June 11 when I upgraded to the commit listed above. Yesterday (on the new version)I had a system crash and got the `txns-empty` error after restarting, so I tried applying the patch (line #458 in `contractcourt/chain_arbitrator.go b/contractcourt/chain_arbitrator.go`):
```
        // Finally, we'll launch all the goroutines for each watcher and
        // arbitrator so they can carry out their duties.
        for _, watcher := range c.activeWatchers {
                if err := watcher.Start(); err != nil {
                        return err
                }
        }
        for _, arbitrator := range c.activeChannels {
                if err := arbitrator.Start(); err != nil {
                        continue
                }
        }
```
...and now I get this nil pointer error above.

**Comment by Roasbeef** [comment]
Ahh, ok that makes sense re the commit you were running before hand. Try this
```go
diff --git a/contractcourt/channel_arbitrator.go b/contractcourt/channel_arbitrator.go
index 0ee68313..db5ddb04 100644
--- a/contractcourt/channel_arbitrator.go
+++ b/contractcourt/channel_arbitrator.go
@@ -440,6 +440,9 @@ func (c *ChannelArbitrator) stateStep(triggerHeight uint32,
 		// We'll tell the switch that it should remove the link for
 		// this channel, in addition to fetching the force close
 		// summary needed to close this channel on chain.
+		if c.cfg.ForceCloseChan == nil {
+			return c.state, nil, nil
+		}
 		closeSummary, err := c.cfg.ForceCloseChan()
 		if err != nil {
 			log.Errorf("ChannelArbitrator(%v): unable to "+
```

**Comment by pinheadmz** [comment]
Thanks 'beef! I'm up and running now (although with 13 channels open I still can't find route to LTB-tip, satoshis place or mainnet yalls... but I'll keep trying)

In slack I heard advice to close all channels and rebuild the node from latest master to avoid re-patching with every upgrade... do you concur? Or, how else should I proceed now that I can access my lnd node again.

**Comment by Roasbeef** [comment]
What error do you get for those? I'm able to pay np (well idk what node or set up LTB-tip is running but works for the others). 

Yeah that's one route, although there's a PR to add a `forgetchannel` RPC which would let you delete borked channels like this (if they're negligible).

**Comment by pinheadmz** [comment]
`"payment_error": "unable to find a path to destination",` LTB runs C-lightning, I think my direct channel to them is closed now but I had one and was able to tip and also my node forwarded a hop or two.

My node has been down for a few days, looks like its still receiving new channel announcements so I might not be up to date with the network graph just yet

**Comment by Roasbeef** [comment]
That's it? No other error? If you get that, then would mean the dest isn't even in your graph (if you get that the first time).

**Comment by pinheadmz** [comment]
Well satoshis place is in my peers, but no direct channel. `queryroutes` also reports `unable to find a path to destination` 

but again, I'm seeing a lot of `new channel discovered` in my log... I'm gunna let it soak for an hour then try again

**Comment by pinheadmz** [comment]
update: after opening a new channel to satoshis place I was able to make payments to all three destinations above. Ive had this problem before where my channel to LTB was blocking me from making any other payments, because all routes started with that channel. Anyway thanks again! Im running

**Comment by pinheadmz** [comment]
Installed 0.5 from compiled binaries and getting same error in log:
```
2018-09-25 09:52:20.791 [ERR] SRVR: unable to start server: -26: 16: bad-txns-vout-empty

-26: 16: bad-txns-vout-empty
```

previously I was running
`"version": "0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19"`
with this patch applied: https://github.com/lightningnetwork/lnd/issues/1306#issuecomment-398122172

**Comment by vegardengen** [comment]
The code has changed a bit. I had the same patch. This is the one I had to use at 0.5:

```
diff --git a/contractcourt/chain_arbitrator.go b/contractcourt/chain_arbitrator.go
index db40173..69462db 100644
--- a/contractcourt/chain_arbitrator.go
+++ b/contractcourt/chain_arbitrator.go
@@ -470,7 +470,7 @@ func (c *ChainArbitrator) Start() error {
        for _, arbitrator := range c.activeChannels {
                if err := arbitrator.Start(); err != nil {
                        c.Stop()
-                       return err
+                       continue
                }
        }

```

The good news is that if you compile master plus this patch, and run the lnd-debug binary from the source directory (that are created when you do make), you will be able to delete this channel. There exists an lncli abandonchannel command that takes the same arguments as lncli closechannel. You can then go back to run stock lnd, having gotten rid of the dust channel(s).

**Comment by pinheadmz** [comment]
@vegardengen thanks this is essentially what I did.
I applied both patches described in this thread on top of 0.5 master just so I could even run it. Switched on debug mode and compiled. Then used abandonchannel to abandon the 1000 satoshi channel that was causing the headache. I think I'm all good now!
