### ISSUE TITLE
Re-used on-chain address, funds not showing up after multiple confirmations

### ISSUE THREAD

**Issue by dognip** [lightningnetwork/lnd#1736]
### Background

Had a working setup using stadicus guide, 3 channels open with autopilot. Next day sent more BTC to address used previous day but it did not show up under unconfirmed balance or anywhere else. Updated LND to latest master. Still not there.
"version": "0.4.2-beta commit=90cdc9da8f60dd94d99d61fd9e86a7ffd39b3b1b"

### Your environment

"version": "0.4.2-beta commit=90cdc9da8f60dd94d99d61fd9e86a7ffd39b3b1b"
raspbian 

### Steps to reproduce

Be silly and use old BTC address

### Expected behaviour

Wallet balance correct

### Actual behaviour

Wallet balance incorrect

**Comment by wpaulino** [comment]
Not able to reproduce this. Are there any relevant `lnd` logs?

**Comment by dognip** [comment]
Not sure how to get logs.. if you can instruct me I will check. 

Mainnet. Originally used the latest release version with stadicus guide. Everything worked well yesterday. Opening and closing channels etc. Today I went to increase the amount of btc to 'get serious' and reused the old address to send in funds. The tx went through, lots of confirmations, but never showed under unconfirmed or in confirmed in wallet. If you ask specific questions I will do my best to track down whatever information is necessary. Thanks

**Comment by dognip** [comment]
In the channel you asked me to check if I'm still receiving notifications from bitcoind. Not sure how to verify that but when I monitor the debug.log and lnd: https://imgur.com/a/OdkhRce

And getblockchaininfo shows blocks and headers are up to date.

At the risk of embarrassment (for how much I've burned...): This tx never went through: https://www.smartbit.com.au/tx/950c1fc489610ce7df5565ef8a51e567c49c6460a7b426046274bbd03a2a4a58

There was never any indication that my lnd wallet recognized it at all. Never went into unconfirmed, or confirmed, or listchaintxns etc.

All previous txs to that address were immediately autopiloted: https://www.smartbit.com.au/address/3E6j7EYButoyfeybjb79dFjJQqNZJsfcCs

**Comment by dognip** [comment]
Would recreating from seed help? I might be wrong, but if the LND wallet is like others I may be able to just import the seed into a traditional wallet? At this point I think I want to just get my funds safe, and recreate my LND setup a bit slower this time...

**Comment by dognip** [comment]
I wanted to emphasize the I had first installed LND from the latest release version (wget https://github.com/lightningnetwork/lnd/releases/download/v0.4.2-beta/lnd-linux-arm-v0.4.2-beta.tar.gz). It was under this version that issues occured. I'm not sure if that had the new aezeed seed type or not.

**Comment by Roasbeef** [comment]
@dognip why does that transaction have an OP_RETURN output? We don't create transactions like that on our end? 

Yes, you can restore from seed using the `lncli create` command. It'll prompt you for an _existing_ seed on startup, that'll be used to do a rescan from the birthday of the wallet to recover funds. 

Yes, that release has the seed format, but it's very old at this point, and has many bugs which have been fixed in master. We'll be releasing a new version (0.5) very soon within the next few days.

**Comment by Roasbeef** [comment]
I attempted to reproduce: receiving from an address twice, and one time the paying transaction has an OP_RETURN output, and the funds showed up no problem. If you update to the latest version, does the issue still persist?

**Comment by dognip** [comment]
I sent that transaction, and all txs, with bitcoin lightning wallet for Android V0.1-61. I have no idea why it has an op_return output. I updated to the latest master as of yesterday and the error still persisted.

Are you somewhat implying I should wait a few days for a new release version? I have no issue with doing so, just want to follow whatever steps you are suggesting.

Thanks so much for helping. I'm clearly out of my depth and I appreciate so much all the support I have received thus far.

**Comment by Roasbeef** [comment]
Ah ok, strange that it added the op_return, I manually made a similar transaction, and was able to pick it up just fine. 

>  I updated to the latest master as of yesterday and the error still persisted.
If it was the case that a _prior_ version caused you to miss the block, then upgrading wouldn't help unless you triggered a manual rescan. 

One option at this point is to attempt a seed recovery. So this would entail making a _new_ node (but still save the data of the old node), and input your seed during `lncli create`. Alternatively, you can drop the txstore entirely, but this would trigger a _full_ rescan of the entire chain which will take some time. Instead I recommend trying to restore from your seed. Note that if you restore from your seed, your channel state won't _yet_ be carried over. As a result, I recommend that you close out your existing channels before attempting this. 


Do you have any logs from the point where you send the funds to deposit?

**Comment by dognip** [comment]
I will attempt to create a new node. Thanks.

I do have logs around the time of the failed tx. I will send them to you (if you want) when I get back to the office on Monday. As far as I could tell, though, the logs and the node completely ignored the tx. 

Its a strange thing...

**Comment by Roasbeef** [comment]
It may have been the case that lnd missed the notification from bitcoind.
In master we now ensure that we don't miss the notifications by splitting
the tx stream from the block stream. At times in the past, the tx stream
would overwhelm the blockstream, leading to missed blocks.

Make sure you _save_ the old node state before you make a new one. The
`lncli create -h` should have enough info to walk thru the recovery steps.

**Comment by dognip** [comment]
hmm.

ok. my plan was to buy a new raspberry pi leaving my current one intact and try to work it out from there

are you saying the lncli create -h will prompt me to save the 'state' of the old node? tbh, im not really even sure what that means.

Thanks

**Comment by dognip** [comment]
As an FYI I've closed all my channels some time ago.

**Comment by Roasbeef** [comment]
Oh no, that'll just show the help for the command. It's interactive, so it'll prompt you for the seed.

**Comment by Roasbeef** [comment]
Also can you show us the output of the following commands: `lncli listchaintxns`, `lncli channelbalance`, `lncli walletbalance`, `lncli pendingchannels`, `lncli listchannels`. I have a new hunch, just want to confirm, thanks!

**Comment by dognip** [comment]
Hi Roasbeef. Sorry for the long delay.

Here is the return from those commands, executed in the order you listed:

https://pastebin.com/0YJrGiYC

I have still not recovered funds as of yet. I'm waiting for a final release to update to. I have run into issues attempting to install from a build. Thanks for all your help!

**Comment by Roasbeef** [comment]
@dognip you can use the recovery mode from your current build.

**Comment by dognip** [comment]
Hi roasbeef. I have attempted two use lncli create multiple times with older installs, and lately the rc1. Everything seems to work out ok (though i have had some problems with macaroons being created in the wrong place, I think this just might be an artifact of me installing over old builds {https://github.com/lightningnetwork/lnd/issues/890}) but I have yet to recover my funds. Each time the wallet balance shows up as empty...

I have tried increasing the look-ahead to 500, but I have no idea what that option really does. Any additional assistance would be greatly appreciated. Thanks!

**Comment by dognip** [comment]
I spoke too soon apparently. The only difference I made in this last attempt, as far as I know, was the look-ahead to 500. I'm not sure that really did anything, but regardless, I now see a balance. Thank you so very much for your help here (and for working on the LN in general)!

Have a great day!

**Comment by Smiggel** [comment]
@dognip, where did you set the look-ahead to 500? Have the same kind of issue.

**Comment by halseth** [comment]
@Smiggel you can set it using the parameter `--recovery_window` in `lncli unlock`.
