### ISSUE TITLE
LND created a multi-sig address for a force-closing channel. 

### ISSUE THREAD

**Issue by zenderady** [lightningnetwork/lnd#1848]
I opened a channel for 700k sat with 1sat fee for the miners. I didn't know that LND could have problems with the fee estimation. The transaction that LND created had too low fee even for propagation. Now the transaction got stuck and the whole balance was unconfirmed. 3 weeks pass and nothing happens. After some discussions with users I decided to try to force-close the pending channel. When I did this, a new transaction was created, and both transactions (channel open and force close) are mined in the same block:

Channel opening tx:
https://www.smartbit.com.au/tx/48c80c15187b39b9dd5020393ade6e55d1bbde0442a3c0ce608c9ee1c07d32a2

Channel force close tx:
https://www.smartbit.com.au/tx/c2fe13219fbd4c9878d65928a80922e7e5f610260915312b1746e4e62e54113e

At this point the unconfirmed balance is unstuck and I sweep the wallet to a new address in LND. If you look at the closing tx, LND sent the amount (700k sat minus fees) to a funding multisig address when it should have sent to a normal address, and this amount in the funding address can not be found on my LND wallet. This closing address (bc1qt0jeqr9ne9r6ekdypargnnqxvjv0d4ypt6ayr90s24kvfd5waxfquw644z)  is not in my "listchaintxns", nor do I have this channel in "listchannels".  This amount is also not in my wallet.

### Your environment
"version": "0.4.2-beta commit=72aa79692cf4960ad27526358e333ba81e8ad99b"
Bitcoind full node

**Comment by cfromknecht** [comment]
Hi @zenderady, 

> If you look at the closing tx, LND sent the amount (700k sat minus fees) to a funding multisig address when it should have sent to a normal address

Nothing here looks out of the oridnary to me, it looks like a standard force close. FWIW, the funds got send to a timelocked P2WSH address, not a multisig.

It seems though that this address has not been swept. What do you see in `pendingchannels`?

**Comment by zenderady** [comment]
znd@znd-desktop:~$ lncli pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [

**Comment by zenderady** [comment]
I have no pending channel, and more than 2016 blocks have passed. What should have happened with the timelocked P2WSH address?

**Comment by cfromknecht** [comment]
> What should have happened with the timelocked P2WSH address?

LND should have broadcast one more txn that then sweeps the funds back into your wallet. The fact that it is missing from `pendingchannels` is odd, does this channel show up in `lncli closedchannels`? 

My current guess is that the opening and closing txns confirming in the same block is responsible for this final sweep txn never being made. Some work has been done in this area in the last month, so it's possible the bug here has already been fixed in master. Note however that upgrading may not resolve the issue automatically.

Are you able to provide any logs, specifically after a restart? It might be useful to turn up the logging level to debug for the `CNCT` and `UTXN`.

**Comment by zenderady** [comment]
Lncli closedchannels shows up empty. 
Unfortunatelly I don't have logs from that period as I didn't know I am missing those funds. After a friend on slack told me that the transaction got mined (we thought it never went through) we started to do that maths and see that the amount is missing. 
Should I just write off this amount so I don't have to think about it?

**Comment by zenderady** [comment]
I have provided logs but this issue still is not resolved. The 700k sat are still in the last address but I do not see them in my walletbalance.
This is the last address:
https://www.smartbit.com.au/address/bc1qt0jeqr9ne9r6ekdypargnnqxvjv0d4ypt6ayr90s24kvfd5waxfquw644z

**Comment by Roasbeef** [comment]
That's a p2wsh address. That's not a regular address. It still seems to be the case that the transaction wasn't confirmed due to the fee being too low. Once we get #1704 in, then it will be able to re-sign the transaction with a higher fee, and get that into a block.
