### ISSUE TITLE
Cannot get list of CONFIRMED transactions via RPC (getTransactions)

### ISSUE THREAD

**Issue by weaklysubjective** [lightningnetwork/lnd#2415]
### Background

Closed channel between two nodes. Close is complete. Logs suggest the transaction was inserted correctly. Block explorer shows the transaction as it reaches its required confirmations (3)

GetTransaction RPC response shows 0 confirmation, and no blockhash.

#1422 suggests this issue is similar to that issue, however in that case it was unconfirmed transaction. 

The LNDs use neutrino and the transaction in question has reached the required confirmations.

### Your environment

* version of `lnd` --- 0.5.0 beta with neutrino on testnet
* which operating system (`uname -a` on *Nix) --- iOS
* version of `btcd`, `bitcoind`, or other backend  -- btcd 

### Steps to reproduce

Close channel. Observe responses received from GetTransactions
It will show zero confirmations even when the transaction is entirely confirmed

### Expected behaviour

GetTransaction to reflect confirmations and blockhash accurately

### Actual behaviour

Neither confirmation nor block hash is available

LOG
===
2019-01-04 18:01:01.009 [INF] LNWL: Inserting unconfirmed transaction e24894006a22b5cf89182fcf4e30d9939ae99f1d787ade9dadf2b89ccd2b9907
2019-01-04 18:01:01.540 [INF] HSWC: Removing channel link with ChannelID(33eed972dd732056122a1391b3a94ec1a121f796621bda3cdae9d7e961d8e780)
2019-01-04 18:01:01.541 [INF] PEER: Waiting for confirmation of cooperative close of ChannelPoint(80e7d861e9d7e9da3cda1b6296f721a1c14ea9b391132a12562073dd72d9ee33:0) with txid: e24894006a22b5cf89182fcf4e30d9939ae99f1d787ade9dadf2b89ccd2b9907
2019-01-04 18:01:01.543 [INF] NTFN: New confirmations subscription: txid=e24894006a22b5cf89182fcf4e30d9939ae99f1d787ade9dadf2b89ccd2b9907, numconfs=1, height_hint=1450920

**Comment by weaklysubjective** [comment]
**Update:** 
Remote node shows accurate current status of the tx in question - including the correct number of confirmations, block hash etc. 
Originating node (i.e. node that initiated the channel open) however does not show any of those details - shows 0 for number of confirmations, and block hash is blank

**Comment by Roasbeef** [comment]
Does this persist if you update to 0.5.1? A number of bugs related to transaction display with neutrino were fixed since then.

**Comment by weaklysubjective** [comment]
Guess its about time for me to update ..i have been holding off in the event update caused other issues. Brb with an update.

**Comment by weaklysubjective** [comment]
Hi guys, upgraded to 0.5.1 in the hope changes to neutrino etc may show the tx with confirmations and block hash (previously it showed with 0 confirmations and no block hash). With 0.5.1 the tx doesn't show at all on the offending node. The good node still shows the complete tx.

**Comment by Roasbeef** [comment]
Resolved offline.
