### ISSUE TITLE
LND panic: invalid page type (0.6.0-beta Arm/Raspiblitz)

### ISSUE THREAD

**Issue by fluidvoice** [lightningnetwork/lnd#3040]
### Background
Upgrading from RaspiBlitz v1.1 to v1.2 (also upgrades LND) fails with an lnd panic:
**[edit] not specific to 0.6.0 or v1.2 as has been happening for a while**
"panic: invalid page type"
Open Raspiblitz issue: https://github.com/rootzoll/raspiblitz/issues/494#issuecomment-489328678

### environment
LTND: Version: 0.6.0-beta commit=v0.6-beta, build=production
Raspbian/Raspberry Pi (RaspiBlitz)

### Steps to reproduce

Install Raspiblitz v1.2 on top of v1.1 and restart

### Expected behaviour

bitcoind and lnd syncs, unlock wallet, and display normal running menu on screen

### Actual behaviour

LND shuts down with errors

**Comment by fluidvoice** [comment]
## LOGS

raspiblitz: https://termbin.com/l68f
syslog: https://termbin.com/ec8e
bitcoind: https://termbin.com/6xt4
lnd: https://termbin.com/pwwu

**Comment by fluidvoice** [comment]
In syslog:

May  4 14:01:34 wuestenigelRaspi lnd[22599]: 

> #011/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnd.go:477 +0x14
> May  4 14:01:34 wuestenigelRaspi systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> May  4 14:01:34 wuestenigelRaspi systemd[1]: lnd.service: Unit entered failed state.
> May  4 14:01:34 wuestenigelRaspi systemd[1]: lnd.service: Failed with result 'exit-code'.
> May  4 14:02:34 wuestenigelRaspi systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
> May  4 14:02:34 wuestenigelRaspi systemd[1]: Stopped LND Lightning Daemon.
> May  4 14:02:34 wuestenigelRaspi systemd[1]: Starting LND Lightning Daemon...
> May  4 14:02:34 wuestenigelRaspi systemd[1]: Started LND Lightning Daemon.

**Comment by fluidvoice** [comment]
turns out this panic has been a problem for the user for a while, not just when upgrading to Raspiblitz v1.2
Could it be something corrupted on disk?  I recommended backup his wallet and re-install from scratch.

**Comment by halseth** [comment]
Could you try running the `bolt` compact tool on the corrupt db? Sometimes that helps!

**Comment by fluidvoice** [comment]
dunno what that is.  Atm, I'm trying to compile 0.6-beta-rc1 to test it.

**Comment by fluidvoice** [comment]
OK got past that.  Build continuing...

admin@thunda:~/raspiblitz/lnd $ make

> cat: go.mod: No such file or directory
> go: finding github.com/golang/protobuf/jsonpb latest
> go: finding github.com/golang/protobuf/proto latest
> go: finding github.com/lightningnetwork/lnd/walletunlocker latest
> go: finding github.com/lightningnetwork/lnd/lnrpc latest
> go: finding github.com/btcsuite/btcd/chaincfg/chainhash latest
> go: finding github.com/btcsuite/btcd/wire latest
> go: finding google.golang.org/grpc/codes latest
> go: finding google.golang.org/grpc/status latest
> go: finding golang.org/x/net/context latest
> go: finding golang.org/x/crypto/ssh/terminal latest
> go: finding golang.org/x/net latest
> go: finding golang.org/x/crypto/ssh latest
> go: finding golang.org/x/crypto latest
> go: finding github.com/btcsuite/btcd/chaincfg latest
> go: finding github.com/btcsuite/btcd latest
> go: downloading github.com/btcsuite/btcd v0.0.0-20190427004231-96897255fd17
> go: extracting github.com/btcsuite/btcd v0.0.0-20190427004231-96897255fd17
> go: finding github.com/kkdai/bstream v0.0.0-20161212061736-f391b8402d23
> go: finding github.com/btcsuite/go-socks v0.0.0-20170105172521-4720035b7bfd
> go: finding github.com/btcsuite/winsvc v1.0.0
> go: finding github.com/btcsuite/websocket v0.0.0-20150119174127-31079b680792
> go: finding github.com/onsi/ginkgo v1.7.0
> go: finding github.com/davecgh/go-spew v0.0.0-20171005155431-ecdeabc65495
> go: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d
> go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
> go: finding google.golang.org/appengine v1.1.0
> go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
> go: finding github.com/jessevdk/go-flags v0.0.0-20141203071132-1679536dcc89
> go: finding github.com/btcsuite/btcutil v0.0.0-20190425235716-9e5f4b9a998d
> go: finding github.com/client9/misspell v0.3.4
> go: finding github.com/btcsuite/snappy-go v0.0.0-20151229074030-0bdef8d06723
> go: finding golang.org/x/lint v0.0.0-20190313153728-d0100b6bd8b3
> go: finding github.com/jrick/logrotate v1.0.0
> go: finding golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
> go: finding github.com/onsi/gomega v1.4.3
> go: honnef.co/go/tools@v0.0.0-20190102054323-c2f93a96b099: unrecognized import path "honnef.co/go/tools" (https fetch: Get https://honnef.co/go/tools?go-get=1: net/http: TLS handshake timeout)
> go: finding golang.org/x/crypto v0.0.0-20170930174604-9419663f5a44
> go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a
> go: finding github.com/aead/siphash v1.0.1
> go: finding github.com/golang/protobuf v1.2.0
> go: finding golang.org/x/text v0.3.0
> go: finding github.com/golang/mock v1.1.1
> go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
> go: finding github.com/BurntSushi/toml v0.3.1
> go: finding github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
> go: finding golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
> go: finding github.com/btcsuite/btclog v0.0.0-20170628155309-84c8d2346e9f
> go: finding cloud.google.com/go v0.26.0
>

**Comment by halseth** [comment]
@fluidvoice Are you trying the instructions from the release notes? There was an error there, I just corrected it so you can try again.

**Comment by fluidvoice** [comment]
Now here...

> go: finding github.com/btcsuite/seelog latest
> go: finding github.com/roasbeef/btcd/rpctest latest
> go: finding github.com/roasbeef/btcd latest
> go: finding github.com/lightningnetwork/lnd/walletunlocker latest
> build github.com/rootzoll/raspiblitz/lnd/cmd/lncli: cannot load github.com/lightningnetwork/lnd/walletunlocker: cannot find module providing package github.com/lightningnetwork/lnd/walletunlocker
> go: finding github.com/btcsuite/seelog latest
> go: finding github.com/roasbeef/btcd/rpctest latest
> go: finding github.com/roasbeef/btcd latest
> go: finding github.com/lightningnetwork/lnd/walletunlocker latest
> build github.com/rootzoll/raspiblitz/lnd/cmd/lncli: cannot load github.com/lightningnetwork/lnd/walletunlocker: cannot find module providing package github.com/lightningnetwork/lnd/walletunlocker
>  Building debug lnd and lncli.
> GO111MODULE=on go build -v -tags="dev" -o lnd-debug -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v1.1-650-g66ca40ee0d82aa7e9c33fe0f02bd76b5cfe0af8f" github.com/lightningnetwork/lnd
> Fetching https://github.com?go-get=1
> go: finding github.com/btcsuite/seelog latest
> go: finding github.com/roasbeef/btcd/rpctest latest
> go: finding github.com/roasbeef/btcd latest
> Parsing meta tags from https://github.com?go-get=1 (status code 200)
> build github.com/lightningnetwork/lnd: cannot load github.com/BitfuryLightning/tools/routing: cannot find module providing package github.com/BitfuryLightning/tools/routing
> Makefile:94: recipe for target 'build' failed
> make: *** [build] Error 1

**Comment by fluidvoice** [comment]
> @fluidvoice Are you trying the instructions from the release notes? There was an error there, I just corrected it so you can try again.

I was just going by what I read in the MAKEFILE.md 
I will take a look at the release notes and see what I'm doing wrong.

**Comment by fluidvoice** [comment]
was not. trying now

**Comment by fluidvoice** [comment]
Tried again still fails - complete build output: 
https://github.com/lightningnetwork/lnd/issues/3025#issuecomment-489777426

**Comment by cfromknecht** [comment]
@fluidvoice there seems to be an issue with your go installation that carried over files from a previous version of the source code, which cause those methods to be declared twice. (this has happened to be me before as well)

This issue https://github.com/golang/go/issues/30402 suggests removing `/usr/local/go` and then try reinstalling

**Comment by fluidvoice** [comment]
> @fluidvoice there seems to be an issue with your go installation that carried over files from a previous version of the source code, which cause those methods to be declared twice. (this has happened to be me before as well)
> 
> This issue [golang/go#30402](https://github.com/golang/go/issues/30402) suggests removing `/usr/local/go` and then try reinstalling

@cfromknecht my build problem was resolved: https://github.com/lightningnetwork/lnd/issues/3025#issuecomment-489821258

**Comment by cfromknecht** [comment]
> Yes, my build problem was resolved by removing and reinstalling go 

@fluidvoice glad to hear you got it resolved, it was definitely confusing the first time i encountered it

Unfortunately though, your database does appear to be corrupted. What version was running when the error started initially? If it happened on a pre 0.6 version, it was known issue that was fixed by #2842, but there isn't a whole lot we can do otherwise I'm afraid

**Comment by fluidvoice** [comment]
> Unfortunately though, your database does appear to be corrupted.

Are you sure? ... https://github.com/lightningnetwork/lnd/issues/3025#issuecomment-490100996
~/raspiblitz/lnd $ `sudo /home/admin/raspiblitz/lnd/bin/bbolt check /mnt/hdd/lnd/data/graph/mainnet/channel.db`
OK

**Comment by wpaulino** [comment]
Will be closing this as it's just database corruption. @fluidvoice we can continue with your issue in #3025.
