### ISSUE TITLE
"the passed output does not belong to the wallet" when attempting to bump fee

### ISSUE THREAD

**Issue by NateNate60** [lightningnetwork/lnd#5199]
### Background

I recently tried to close a channel but the closing transaction has too low a fee. However, when I try to bump the fee, the wallet claims that the output does not belong to the wallet. The transaction ID appears in `lncli listchaintxns`:

```
nate@nates-server:~$ lncli listchaintxns | grep "c36ffcdd245425a1c0bbbdaf65693f4dbe1e050d5a29e1aa9d2079d4ba7cc925"
            "tx_hash": "c36ffcdd245425a1c0bbbdaf65693f4dbe1e050d5a29e1aa9d2079d4ba7cc925",
```

### Your environment

* `lnd version 0.12.1-beta commit=v0.12.1-beta`
* Ubuntu 20.04 LTS, AMD64, kernel 5.4.0-70-generic
* Bitcoin Core version v0.21.0

### Expected behaviour

Closing transaction is bumped, using CPFP or RBF

### Actual behaviour

```
nate@nates-server:~$ lncli wallet bumpfee c36ffcdd245425a1c0bbbdaf65693f4dbe1e050d5a29e1aa9d2079d4ba7cc925:1 --sat_per_byte 20
[lncli] rpc error: code = Unknown desc = the passed output does not belong to the wallet
```

**Comment by NateNate60** [comment]
I see three possible solutions to this that I could take:

* Extracting the private key for that address or for all addresses and importing it into Electrum, then spending the change output (I've heard this is not possible with LND)
* Getting the peer to sign another transaction with a higher fee
* Paying a mining pool a rather high price ($120) to mine the transaction.

**Comment by alexbosworth** [comment]
You could try force closing if that has a higher fee rate

**Comment by NateNate60** [comment]
> You could try force closing if that has a higher fee rate

I tried that before and force-closing it will cause it to tell me that it's already closing.

**Comment by alexbosworth** [comment]
You can try restarting LND which should cause it to rebroadcast

**Comment by Roasbeef** [comment]
Do you see the transaction in bitcoind's mempool on restart of lnd? It should be rebroadcast on restart if the transaction is actually valid (it may be the case that the fee rate was too low perhaps).

**Comment by wpaulino** [comment]
@NateNate60 just to confirm, are you providing the correct output index that corresponds to you to the `bumpfee` command?

**Comment by NateNate60** [comment]
> @NateNate60 just to confirm, are you providing the correct output index that corresponds to you to the `bumpfee` command?

Yes

**Comment by wpaulino** [comment]
I don't see how this error is possible then. The closing transaction exists in your wallet (shows up in `listchaintxns`), so `bumpfee` should be able to find the corresponding address for your output. Have you tried an output index of `0`?

**Comment by NateNate60** [comment]
Yes, I've tried an output index of zero.

I also closed another channel in the meantime, that was supposed to close with a fee of 15 sat/B

```
nate@nates-server:~$ lncli closechannel --funding_txid 2023221db5ad105548013013e801d37be099d5afbb664877ba90e11addfa2d99 --sat_per_byte 15
```

Which produced output transaction [d41c73058e06545e422d7111025668ff1e018a673da994b155f65e324ee4e390](https://mempool.space/tx/d41c73058e06545e422d7111025668ff1e018a673da994b155f65e324ee4e390), but it only has a feerate of 1 sat/B. So it ignored my preference and closed with 1 sat/B. I similarly can't bump the fee on this transaction.

In addition, the command hasn't finished executing yet, an hour later:

![image](https://user-images.githubusercontent.com/41277019/114468807-e7be1980-9ba0-11eb-94e4-62e5e6e8866e.png)

Some really strange behaviour is going on here.

**Comment by NateNate60** [comment]
```
nate@nates-server:~$ lncli wallet bumpfee d41c73058e06545e422d7111025668ff1e018a673da994b155f65e324ee4e390:1 --sat_per_byte 30
[lncli] rpc error: code = Unknown desc = the passed output does not belong to the wallet
nate@nates-server:~$ lncli wallet bumpfee d41c73058e06545e422d7111025668ff1e018a673da994b155f65e324ee4e390:0 --sat_per_byte 30
[lncli] rpc error: code = Unknown desc = the passed output does not belong to the wallet
nate@nates-server:~$ 
```

**Comment by NateNate60** [comment]
I've also tried this:

```
nate@nates-server:~$ lncli wallet bumpclosefee 2023221db5ad105548013013e801d37be099d5afbb664877ba90e11addfa2d99:0 --sat_per_byte 30
nate@nates-server:~$ 
```

It appears to do nothing.

**Comment by wpaulino** [comment]
> I also closed another channel in the meantime, that was supposed to close with a fee of 15 sat/B
nate@nates-server:~$ lncli closechannel --funding_txid 2023221db5ad105548013013e801d37be099d5afbb664877ba90e11addfa2d99 --sat_per_byte 15
Which produced output transaction d41c73058e06545e422d7111025668ff1e018a673da994b155f65e324ee4e390, but it only has a feerate of 1 sat/B. So it ignored my preference and closed with 1 sat/B. I similarly can't bump the fee on this transaction.

Aha, so this channel seems to have been force closed, even though you didn't provided the `--force` flag (or perhaps you omitted it above). When a channel is force closed (assuming it's not a channel with anchor outputs), it uses a pre-negotiated fee. Force closing also doesn't give you access to the funds immediately, they will be swept to your wallet after the CSV delay. This is why `bumpfee` does not work in this scenario. I'm assuming this is likely what happened with the other channel as well?

> I've also tried this:
nate@nates-server:~$ lncli wallet bumpclosefee 2023221db5ad105548013013e801d37be099d5afbb664877ba90e11addfa2d99:0 --sat_per_byte 30
It appears to do nothing.

`bumpclosefee` only works for channels with anchor outputs (`commitment_type == ANCHORS`).

**Comment by djkazic** [comment]
Is there a reason it chose such a low fee bucket at 1 sat/vB? At current mempool rates that's unlikely to ever confirm. Does this mean potentially waiting months if not years for the force close to go through?

**Comment by wpaulino** [comment]
@djkazic if fees don't go down within that period, yes. That's why we have channels with anchor outputs now (still not enabled by default, has some implications on wallet balance). As for why it's 1 sat/vbyte, it depends. It could be that the last fee negotiation happened at a time fees were low enough and the peers haven't reconnected since. At least one fee update per hour of channel uptime is attempted by lnd.

**Comment by djkazic** [comment]
Would NateNate be able to use CPFP on his `p2wsh` output in the force close txs? TXIDs are `d41c73058e06545e422d7111025668ff1e018a673da994b155f65e324ee4e390` and `89bacd117c615759c8120ed3b3dc54701adcb782f9b84275bbd2dab416125482`

**Comment by wpaulino** [comment]
That's not supported at the moment, only wallet-owned outputs are eligible for CPFP. Also, lnd waits to sweep time-locked outputs from force closes only after the closing transaction confirms.

**Comment by djkazic** [comment]
Ah darn. Lesson learned. Anchor channels weren't on when this channel was made, they were turned on about a week after. At least it wasn't a larger sum.

**Comment by alexbosworth** [comment]
The side without timelock could try guggero chantools - maybe that can access the key directly for a sweep

**Comment by djkazic** [comment]
That would be @NateNate60. I'll send him a link to https://github.com/guggero/chantools. @alexbosworth do you know what command he'd want to run to sweep the funds given a channel point or funding tx + index?

**Comment by alexbosworth** [comment]
I'm not sure but I would think geninputscript if you want to work directly with the key - this might be a feature request to make there if you don't want to enter the danger zone of working directly with keys

**Comment by wpaulino** [comment]
`chantools` could work though I'm not too familiar with all of its capabilities, you could also try to sweep manually (this is a lot more involved and risky), or just wait for things to confirm. Given how what's happening is expected, I think we can close this?

**Comment by NateNate60** [comment]
@wpaulino @djkazic `chantools rescueclosed` seems to be for force-closed channels. The channel in question was closed co-operatively. Sorry for the late response. I've been a bit busy lately, hopefully this issue hasn't been abandoned

**Comment by wpaulino** [comment]
There is a P2WSH script present in the closing transaction [d41c73058e06545e422d7111025668ff1e018a673da994b155f65e324ee4e390](https://mempool.space/tx/d41c73058e06545e422d7111025668ff1e018a673da994b155f65e324ee4e390), which is not possible for co-op closes unless an upfront shutdown address was used -- was that the case here?

**Comment by NateNate60** [comment]
I don't believe I've put an upfront shutdown address.

**Comment by Roasbeef** [comment]
Unfortunately, it seems that you either need to wait or, manually use your SCB to _manually_ extract the public key and then use that to create a custom sweep transaction using the wallet RPC server. 

> The channel in question was closed co-operatively. 

No it's a forced closed channel on chain, so you may be able to use the tools to get the funds our earlier.  @NateNate60

**Comment by alexbosworth** [comment]
Can you get one or the other side to force close? What happens then? fees are down now to 1 sat/vbyte at the bottom so a CPFP should work now

**Comment by wpaulino** [comment]
A [closing transaction already exists](https://blockstream.info/tx/d41c73058e06545e422d7111025668ff1e018a673da994b155f65e324ee4e390?input:0), it's being picked up by different nodes/explorers now as well, so it seems to have propagated throughout the network. It'll likely confirm soon if fees remain low.

**Comment by alexbosworth** [comment]
very cool ok

for future reference the tx is:
```
02000000000101992dfadd1ae190ba774866bbafd599e07bd301e8133001485510adb51d222320000000000076a2f78002801d0300000000002200200628eb30c227eb084a6547f2922f46ad4da8423b22ecb0ef5911462113e52eed39dd0300000000001600146c659aa38552d71f954954ebb9d2b5f32f782037040047304402202821bda52ff052703b6a7388d5765a8618fd43936e6196a7ad3f7b8e89dedd620220707c7cd08e71533ab91a2b9d35dc7396e91f15e03b0ae9ffd4807271b75b233601473044022005c333108a6b6298c72e96074131935bc6deeb34c818e40748da6d63652b6c85022031e211bd2a429309fb1b1c3e2a0ab7dbcfb5dc4a743f8d9b8e2611fcd892b5b601475221027e69caa6b101f70b52c2a1d9acefa64ca1fec378e617802b4a68aade4d54c997210316f27d6f92a42ee268c02c3e29f030cfb76e3b8c9adb43ed319f438cb892116952aeaa5afa20
```

I have it in my own mempool

Whoever is on the non-csv constrained side can use bumpfee on the outpoint to bump the fee now provided they are running lnd

**Comment by wpaulino** [comment]
> Whoever is on the non-csv constrained side can use bumpfee on the outpoint to bump the fee now provided they are running lnd

This actually isn't supported at the moment. The non-delayed side funds are part of the wallet, but they're part of our custom key scope `m/1017'`, while `bumpfee` requires outputs from the default key scopes `m/49'` (NP2WKH) and `m/84'` (P2WKH).

**Comment by alexbosworth** [comment]
Ah interesting to know that - if this doesn't work then could @guggero tool be used to output the remote key and then that UTXO could be imported into another wallet that would allow the CPFP to happen?

**Comment by wpaulino** [comment]
I double checked and my comment above is incorrect. It should be picked up by `bumpfee` regardless of the key scope the funds belong to, the only prerequisite is that the transaction crediting the funds (i.e., the transaction containing the output that pays to you and you wish to bump) exists within the wallet. This usually isn't the case for remote force closes since only one side is broadcasting the transaction. You can get around this by broadcasting the force close transaction yourself through `WalletKit.PublishTransaction` so that it gets added to lnd's internal transaction store.

**Comment by alexbosworth** [comment]
Oh that's great - also I have a CLI tool on my github if you need a way to hit that publish transaction endpoint

**Comment by NateNate60** [comment]
I suppose since my node initiated the force-close, I'm the constrained, side, correct?

**Comment by djkazic** [comment]
Hi NateNate60, I think ours was the side to initiate force close, actually. So you should be the one with the unlockable output.

**Comment by alexbosworth** [comment]
Whoever it is, I think the command is `lncli wallet bumpfee d41c73058e06545e422d7111025668ff1e018a673da994b155f65e324ee4e390 1 --sat_per_byte <fee rate>` to bump the output

The output of that command should be an empty JSON `{}` and not an error

**Comment by NateNate60** [comment]
That command not working is the entire reason this issue was opened

**Comment by wpaulino** [comment]
@NateNate60 see my [previous comment](https://github.com/lightningnetwork/lnd/issues/5199#issuecomment-832984075) on why the command is not working.

**Comment by alexbosworth** [comment]
Did you try publishing the transaction? If you need more 1 on 1 help you can join the LND slack and DM me I can try and help you through it : https://lightning.engineering/slack.html

**Comment by djkazic** [comment]
The txs just cleared! Thanks for the guidance and help everyone.

**Comment by ktpx** [comment]
Just replying to old post, but same issue trying to bump fee, was resolved by a restart of lnd service.

**Comment by jogc** [comment]
I'm having this issue as well - the close transaction has a very low fee and seems unlikely to confirm anytime soon and I can't bump it (bumpfee gives the passed output does not belong to the wallet for both of its two outputs, closechannel --forcegives channel is already in the process of being force closed). I have tried manually rebroadcasting it as was suggested above but that did not make any difference (the tx is included in listchaintxns by the way). There were also some talk about exporting keys and manually creating CPFP transactions or possibly using chantools. Any pointers?

**Comment by guggero** [comment]
Just to confirm: Is the close TX in your local mempool? Then bumping it should work. Did you re-publish through `lnd` or through `bitcoind` directly? Would try `lncli wallet publishtx` if you did `bitcoind` directly, in order for the wallet to re-add it. There's also the `lncli wallet bumpclosefee` command that you can try.

**Comment by jogc** [comment]
> Just to confirm: Is the close TX in your local mempool? Then bumping it should work. Did you re-publish through `lnd` or through `bitcoind` directly? Would try `lncli wallet publishtx` if you did `bitcoind` directly, in order for the wallet to re-add it. There's also the `lncli wallet bumpclosefee` command that you can try.

I just did a `bitcoin-cli getrawtransaction` and yes its there. `bumpclosefee` says `intercept already started` and the regular `bumpfee` still doesn't work. There are no CPFP transactions published by the way - both of the two outputs of the closing tx are still unspent according to mempool.space. I used `lncli wallet publishtx` to republish it. I got the original txid back so it seemed to have worked.

**Comment by guggero** [comment]
Ah, it seems like the `bumpclosefee` is for CPFPing a force close transaction, not a co-op TX. So after the successful `lncli wallet publishtx` the close transaction is still not listed in `lncli listchaintxns`? Did you specify the correct TXID and output index when running `lncli wallet bumpfee`? You need to specify the coop-close TX and the output index of _your_ output.

**Comment by jogc** [comment]
> Ah, it seems like the `bumpclosefee` is for CPFPing a force close transaction, not a co-op TX. So after the successful `lncli wallet publishtx` the close transaction is still not listed in `lncli listchaintxns`? Did you specify the correct TXID and output index when running `lncli wallet bumpfee`? You need to specify the coop-close TX and the output index of _your_ output.

Yes it's listed in `listchaintxns`, I'm just unable to bump it. In case it matters this channel might have been co-op closed initially and then force-closed later (don't remember exactly). Anyway, it looks like this in pendingchannels (censored):
```
{
    "channel": {
        "remote_node_pub": "PK",
        "channel_point": "CP",
        "capacity": "X",
        "local_balance": "X",
        "remote_balance": "X",
        "local_chan_reserve_sat": "X",
        "remote_chan_reserve_sat": "X",
        "initiator": "INITIATOR_REMOTE",
        "commitment_type": "STATIC_REMOTE_KEY",
        "num_forwarding_packages": "0",
        "chan_status_flags": "ChanStatusBorked|ChanStatusCommitBroadcasted|ChanStatusLocalCloseInitiator",
        "private": false
    },
    "limbo_balance": "X",
    "commitments": {
        "local_txid": "LOCAL-TX",
        "remote_txid": "REMOTE-TX",
        "remote_pending_txid": "",
        "local_commit_fee_sat": "X",
        "remote_commit_fee_sat": "X",
        "remote_pending_commit_fee_sat": "0"
    },
    "closing_txid": "LOCAL-TX"
}
```

I used LOCAL-TX above for `lncli wallet bumpfee`, and I tried both 0 and 1 as index just to be sure. For `bumpclosefee` I used CP obviously.

**Comment by guggero** [comment]
Ah, so it is a force-closing TX, not a co-op close. Then you can't do anything on your end as there is no anchor to CPFP on and your script has a time lock in it so it needs to confirm first. That's the whole problem anchor channels are solving...
Do you have a way to contact the remote peer? If they are running `lnd`, then they can use [`chantools sweepremoteclosed`](https://github.com/lightninglabs/chantools/blob/master/doc/chantools_sweepremoteclosed.md) on their output to CPFP it.

**Comment by jogc** [comment]
> Ah, so it is a force-closing TX, not a co-op close. Then you can't do anything on your end as there is no anchor to CPFP on and your script has a time lock in it so it needs to confirm first. That's the whole problem anchor channels are solving... Do you have a way to contact the remote peer? If they are running `lnd`, then they can use [`chantools sweepremoteclosed`](https://github.com/lightninglabs/chantools/blob/master/doc/chantools_sweepremoteclosed.md) on their output to CPFP it.

Got it. I guess I have to try and find a way of contacting them then. Thank you!
