### ISSUE TITLE
Help Inquiry: Payment IN_FLIGHT stuck, well past blockheight timelock

### ISSUE THREAD

**Issue by miketwenty1** [lightningnetwork/lnd#5393]
I've seen a few tickets describe this same issue. However, I'm unsure of the remedy.

Running `lncli trackpayments <payment hash>` We see some payments with Payment status: IN_FLIGHT that is well past the time lock block height.

Q1: Was this supposed to auto-resolve?

Q2: What are the ways to resolve this? (i.e. some sort of cancel, sendpayment, etc)?
I'm essentially asking what commands to run.

Happy to provide more information if needed.

**Comment by Roasbeef** [comment]
Should be resolved by https://github.com/lightningnetwork/lnd/pull/5214 which will be bundled as part of 0.13

**Comment by miketwenty1** [comment]
@Roasbeef we have been running 0.13 rc3 since it was released.

**Comment by Roasbeef** [comment]
Ok, can you fill out the actual issue template? If those payments were created before upgrading, then they should go to a terminal state after a restart.

**Comment by carlaKC** [comment]
The information about the payment from `ListPayments` would be particularly useful here. Feel free to blank out hashes/route information, only looking for the payment state and the state of each htlc that was dispatched for the payment.

**Comment by miketwenty1** [comment]
@Roasbeef as you requested.. Since this seems like a bug and didn't resolve with upgrading to 0.13.0-beta, I made another ticket.
https://github.com/lightningnetwork/lnd/issues/5396
@carlaKC I have included the information you requested in this new issue
