### ISSUE TITLE
wallet: check we can produce valid signature for address before sending funds on-chain

### ISSUE THREAD

**Issue by papssaj** [lightningnetwork/lnd#7022]
EDIT (guggero):

See [comment below](https://github.com/lightningnetwork/lnd/issues/7022#issuecomment-1278695682), this issue was turned from a bug report into a feature request.

Steps to implement:
 - Before sending any funds on chain, check each output pk script whether it belongs to the wallet.
 - For each output in a transaction that belongs to the wallet, produce a valid spend witness stack and validate it with a script VM to make sure the funds can be spent later on.

Original issue text:

> I have a RaspiBlitz running with the following specifications:
> 
> bitcoin: v23.0.0
> LND: 0.15.2-beta
> 
> A few days ago, I started using clightning in parallel to my LND node on my RaspiBlitz and wanted to now switch over the funds to that lightning node. 
> 
> I closed all channels that the node has, which worked as expected. Now my LND node reports on-chain funds as expected, and also respective UTXOs. However, when I try to sweep the on-chain funds to my normal bitcoin wallet, I get the following error:
> 
> 
> 
> > Unable To Broadcast Sweep Transaction: Unmatched Backend Error: -26: Non-mandatory-script-verify-flag (script Failed An Op_equalverify Operation)
> 
> 
> 
> I already did a rescan of the wallet, and it discovered the same UTXOs again. Can you please advise how I could regain access to my funds? Trying to open a channel to my new lightning instance (clightning) didn't work, it also fails to broadcast the funding transaction and creates channels that stay forever in 'pending' state.
> 
> Update: I managed to identify the UTXO which is causing a problem (by using the 'Lease' functionality in Ride the Lightning). Now there is only one UTXO left. However it has the largest balance so it would be critical to retrieve it.

**Comment by sputn1ck** [comment]
Could you maybe share some logs when trying to sweep the UTXO?

**Comment by guggero** [comment]
I took a very close look at this. The user even provided the affected wallet file (since the funds in the address `bc1qgahgvnsawaenptvl2lfngmwrmjf8ussewhdsk3` that can't be swept were the only ones remaining).
And after careful investigation I'm very sad to say that the only remaining plausible explanation for the problem is some kind of memory corruption at the time the change address was created (before it was stored in the wallet).
All available data in the wallet suggests that the address created (and funds sent to) does not match the private/public key that's stored for it in the wallet. So the funds are basically unspendable.
How this happened is very hard to say (a hardware issue with the RAM, a hardware issue with the storage, a bit flip in the memory/CPU during hashing of the public key).

It is quite hard to write software to protect against such unexpected bit flips. But we discussed this internally and think that we at least should try to create a signature (and verify it) before sending funds to a change address (or any other address the wallet identifies as "its own"). So I'm going to change the title and description of this issue to match that feature request.

**Comment by guggero** [comment]
@papssaj we're trying to gather more information on this. Can you please check Slack, I have a few questions about your hardware and setup. Thanks!

**Comment by ksedgwic** [comment]
Any chance this address is falling afoul of the `Correct BIP-32 derivation issue` fixed in https://github.com/btcsuite/btcutil/pull/182 ?

The generation of the address and later recovery attempt would have to have been on different sides of that fix ... not sure if that is likely ...

**Comment by guggero** [comment]
No, that's the first thing we checked. We actually never switched to the "correct" BIP-32 derivation yet in `lnd`, since a migration is quite tricky. So all keys derived should be consistent within `lnd` (even across recovery and rescans), just not necessarily with other key derivation tools.

But I still have another suspicion what could've mutated the keys and am working on a tool to verify or disprove that suspicion.
