### ISSUE TITLE
Old private channels are not populated in routing hints

### ISSUE THREAD

**Issue by roeierez** [lightningnetwork/lnd#7234]
### Background

Old private channels that were created prior to 0.15.3  (before aliases were introduced) are not populated as routing hints in invoices.

### Your environment

lnd 0.15.3 (mobile)

### Steps to reproduce

1. Open a private channel with old LND version (before the aliases were introduced).
2. Upgrade to LND 0.15.3
3. Create invoice

### Expected behaviour

Invoice should be created with routing hints

### Actual behaviour

Invoice created without routing hints

### Insights

We noticed recently that for some users for specific private channels peer alias is not populated even though the channel with that peer has negotiated the option-scid-alias feature bit. To be more specific the `aliasmgr.GetPeerAlias` function returns with error.
This affects the invoice creation flow as the resulted invoice doesn't contain the routing hints for these channels because in the case `option-scid-alias` was negotiated only the peer alias is used not the real short channel id.

Looking at the db level I see that the alias-bucket is populated but the invoice-alias-bucket (that is used to get routing hint for the invoice) is not. Furthermore these channels are old channels that were not created with aliases but were upgraded to use `option-scid-alias` when LND was upgraded.
In the code I see that the only point where the the invoice-alias-bucket is populated is in the funding/manager.go (handleFundingLocked).
Am I am missing anything or it seems that these private upgraded channels will never have their alias populated and there fore could not be shown as routing hints?

**Comment by positiveblue** [comment]
@roeierez I will try to replicate this but old private channels should have an alias too. Did you migrate from a specific version?

**Comment by roeierez** [comment]
> @roeierez I will try to replicate this but old private channels should have an alias too. Did you migrate from a specific version?

We were migrating from old version yes. 
Can you point me to the code that assign alias to old channels?

**Comment by roeierez** [comment]
I am asking because I only saw such code during the funding process.

**Comment by positiveblue** [comment]
Good question. [Here](https://github.com/lightningnetwork/lnd/blob/ddbe09be870d0e5b3aba45bb3be8d2df6070e4a5/peer/brontide.go#L692) is the flow that old channels should follow after we enabled aliases but the channels do not have one assigned yet.

**Comment by roeierez** [comment]
@positiveblue yes this is the flow indeed but please notice that this flow only call AddLocalAlias: https://github.com/lightningnetwork/lnd/blob/ddbe09be870d0e5b3aba45bb3be8d2df6070e4a5/aliasmgr/aliasmgr.go#L219

But in fact the routing hints are taken from the peer alias that is populated by this method:
https://github.com/lightningnetwork/lnd/blob/ddbe09be870d0e5b3aba45bb3be8d2df6070e4a5/aliasmgr/aliasmgr.go#L345

**Comment by positiveblue** [comment]
I may be wrong here (@Crypt-iQ may throw some light on this) but the idea is that here is:

- We create an alias (A) and send it to our peer in a `fundingLocked` msg. 
- Our peer needs to use that alias (A) for his invoices (route hints field in the invoices)
- Whenever we receive an htlc with an alias that we know, we forward it to that peer.

That means that we have no "control" over the aliases that we have to include in our invoices. It has to be our peers the ones that tell use which alias we can use. From the [spec](https://github.com/lightning/bolts/blob/b38156b9510c0562cf50f8758a64602cc0315c19/02-peer-protocol.md)

> While a node can send multiple alias, it must remember all of the ones it has sent so it can use them should they be requested by incoming HTLCs. The recipient only need remember one, for use in r route hints in BOLT 11 invoices.


As you said, the routing hints are taken from the `invoiceAliasBucket`. And that bucket only gets populated with the information that we receive in `fundingLocked` from our peers where we negotiated `scidAlias`

**Comment by Crypt-iQ** [comment]
> I may be wrong here (@Crypt-iQ may throw some light on this) but the idea is that here is:
> 
>     * We create an alias (A) and send it to our peer in a `fundingLocked` msg.
> 
>     * Our peer needs to use that alias (A) for HIS invoices (route hints field)
> 
>     * Whenever we receive an htlc with an alias that we know, we forward it to that peer.
> 
> 
> That means that we have no "control" over the aliases that we have to include in our invoices. Our peers are the ones that tell use which alias we can use. From the [spec](https://github.com/lightning/bolts/blob/b38156b9510c0562cf50f8758a64602cc0315c19/02-peer-protocol.md)
> 
> > While a node can send multiple alias, it must remember all of the ones it has sent so it can use them should they be requested by incoming HTLCs. The recipient only need remember one, for use in r route hints in BOLT 11 invoices.
> 
> As you said, the routing hints are taken from the `invoiceAliasBucket`. And that bucket only gets populated with the information that we receive in `fundingLocked` from our peers where we negotiated `scidAlias`

This is all correct. @roeierez do you know what implementation your peers are running?

> @positiveblue yes this is the flow indeed but please notice that this flow only call

The assumption here is that if you are peered with an upgraded LND node, it will send `FundingLocked` with an alias if `option-scid-alias` is negotiated. The other node should then receive this and add the alias to their database. An issue might arise if the peer is not an LND node and doesn't have this logic to "upgrade" older channels. 

If this is the case, it should be fixed on our end to always populate the route hints. But it should probably also be fixed on the other implementation (if that's indeed what is happening).

**Comment by positiveblue** [comment]
@roeierez why wouldn't it run anymore? When our peer sends us the [lnwire.FundingLocked message](https://github.com/lightningnetwork/lnd/blob/master/peer/brontide.go#L1521) we will send it to the manager's [fundingMsgs channel](https://github.com/lightningnetwork/lnd/blob/8a18824851941dae471c4de0313cf614d09720bf/funding/manager.go#L1242) and process it in the right [handler](https://github.com/lightningnetwork/lnd/blob/master/funding/manager.go#L3341)


There is [an itest](https://github.com/lightningnetwork/lnd/blob/master/lntest/itest/lnd_zero_conf_test.go#L942) for it. I tried different scenarios and it worked properly. 

In the logic it looks like it is possible to drop some fundingLock messges if we are already processing one, but I doubt that is what happened here.

BTW, if your peer creates an invoice does your node get added properly in his hints?

**Comment by positiveblue** [comment]
@roeierez any updates that can help clarifying the situation?

**Comment by roeierez** [comment]
@positiveblue @Crypt-iQ I missed the exported function ProcessFundingMsg of the funding.Manager and I see you are right about having logic for setting the peer alias when reestablishing the connection.
I am still not sure why it happened for some users but it seems that this issue can be closed.
Thanks for your help and clarifications.

**Comment by positiveblue** [comment]
Even if this part has been cleared out don't hesitate in letting us know if you discover new information about your issue.
