### ISSUE TITLE
[bug]: invalid sweep transaction created on forced close

### ISSUE THREAD

**Issue by rpallai** [lightningnetwork/lnd#7790]
### Background

During force-closing of an anchor channel my node created 3 sweep transactions in total including a probably invalid one and its output is "unconfirmed balance" now. Two sweep txns are confirmed, the third is unknown to the mempool. Seems like lnd tried to spend an unknown output that is not part of my `listchaintxns` list.

`listchaintxns` view of this txn:
```
"tx_hash": "925fc081a33fed20e48a972b65f86b9379602b57241a364f1874ce9184fb936e",
"amount": -1962,
"time_stamp": 1687258739,
"dest_addresses": [
        "bc1pzlpcpl2ewpz490nk6us47zvj72kywsacd6h49drarrd8l6ke9m7sc9euxm"
],
"output_details": [
          {
                  "output_type": 9,
                  "address": "bc1pzlpcpl2ewpz490nk6us47zvj72kywsacd6h49drarrd8l6ke9m7sc9euxm",
                  "pk_script": "512017c380fd59704552be76d7215f0992f2ac4743b86eaf52b47d18da7fead92efd",
                  "amount": 996223,
                  "is_our_address": true
          }
],
"raw_tx_hex": "020000000001025a92582b92954c04a5047c1480c91f75acda6b1c2ce7eb5e4d0e7a5d5180f6f7000000000000000000141c4ee01ad8fee4b928701b275e9275891b40c1288e253df29f1340f1522f7d000000000000000000017f330f000000000022512017c380fd59704552be76d7215f0992f2ac4743b86eaf52b47d18da7fead92efd024830450221009d717792391eb22a282d0f2e431b3fb7c9ecfe4914e2bd3fdc7496cecec3e9f402200634fda586687e97fdcae02478b964fd790fc0fa32f4dc46e088db91d7b7114a01282103a2c927abe7559c81ebf481ef7ba96f0becbc166d0551c5ddf3099f1d459db794ac736460b2680140777db5d5d8cfa2a6049843ee06b341c36caaee8f17a650706c4bb3a466940a6db12ac4d90d75177f5c192e39eb39d76fd984b185c95bdb8cce36421c95ebec2a28220c00",
"label": "0:sweep",
"previous_outpoints": [
        {
                "outpoint": "f7f680515d7a0e4d5eebe72c1c6bdaac751fc980147c04a5044c95922b58925a:0"
        },
        {
                "outpoint": "7d2f52f140139ff23d258e28c1401b8975925e271b7028b9e4fed81ae04e1c14:0",
                "is_our_output": true
        }
]
```
This is the only mention of `f7f680515d7a0e4d5eebe72c1c6bdaac751fc980147c04a5044c95922b58925a:0` in the whole output. This channel is unknown to lnd, blockchain and mempool.

This txn has been created at forced channel close:
```
Jun 20 12:58:19 mother lnd[155267]: 2023-06-20 10:58:19.261 [INF] CNCT: Attempting to force close ChannelPoint(36d16d37800ff72b288d6eeaf9849633d2c2cd4514e6ab03e4dcf40e830b5da7:0)
Jun 20 12:58:19 mother lnd[155267]: 2023-06-20 10:58:19.273 [INF] NANN: Announcing channel(36d16d37800ff72b288d6eeaf9849633d2c2cd4514e6ab03e4dcf40e830b5da7:0) disabled [requested]
Jun 20 12:58:19 mother lnd[155267]: 2023-06-20 10:58:19.364 [INF] CNCT: ChannelArbitrator(36d16d37800ff72b288d6eeaf9849633d2c2cd4514e6ab03e4dcf40e830b5da7:0): force closing chan
Jun 20 12:58:19 mother lnd[155267]: 2023-06-20 10:58:19.407 [INF] CNCT: Broadcasting force close transaction faac6edd32f45fcdf30bac7c4cd1300463226f2e0cb56fcf4c741150cca0ed42, ChannelPoint(36d16d37800ff72b288d6eeaf9849633d2c2cd4514e6ab03e4dcf40e830b5da7:0): (*wire.MsgTx)(0x
4008315ec0)({
Jun 20 12:58:19 mother lnd[155267]:  Version: (int32) 2, [...]
Jun 20 12:58:19 mother lnd[155267]: 2023-06-20 10:58:19.451 [INF] LNWL: Inserting unconfirmed transaction faac6edd32f45fcdf30bac7c4cd1300463226f2e0cb56fcf4c741150cca0ed42
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.505 [WRN] LNWL: Web API does not have a fee rate for target=144, using the fee rate for target=26 instead
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.505 [INF] SWPR: Sweep request received: out_point=faac6edd32f45fcdf30bac7c4cd1300463226f2e0cb56fcf4c741150cca0ed42:0, witness_type=CommitmentAnchor, relative_time_lock=0, absolute_time_lock=0, amount=0.0000033 BTC, params=(fee=144 blocks, force=true, exclusive_group=0x400b81e688)
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.509 [WRN] LNWL: Web API does not have a fee rate for target=144, using the fee rate for target=26 instead
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.509 [INF] SWPR: Sweep request received: out_point=f7f680515d7a0e4d5eebe72c1c6bdaac751fc980147c04a5044c95922b58925a:0, witness_type=CommitmentAnchor, relative_time_lock=0, absolute_time_lock=0, amount=0.0000033 BTC, params=(fee=144 blocks, force=true, exclusive_group=0x400b81e688)
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.512 [INF] NTFN: New spend subscription: spend_id=5, outpoint=faac6edd32f45fcdf30bac7c4cd1300463226f2e0cb56fcf4c741150cca0ed42:0, script=0 463050895eb357420bf0cf419180de450489afbd895ee30165ac4925aaf1161a, height_hint=795175
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.513 [INF] NTFN: Dispatching historical spend rescan for outpoint=faac6edd32f45fcdf30bac7c4cd1300463226f2e0cb56fcf4c741150cca0ed42:0, script=0 463050895eb357420bf0cf419180de450489afbd895ee30165ac4925aaf1161a, start=795175, end=795175
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.513 [WRN] LNWL: Web API does not have a fee rate for target=144, using the fee rate for target=26 instead
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.514 [INF] BTCN: Canceling block subscription: id=4
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.514 [INF] SWPR: Candidate sweep set of size=1 (+1 wallet inputs), has yield=-0.00001829 BTC, weight=677
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.522 [INF] SWPR: Sweep candidates at height=795175 with fee_rate=2772 sat/kw, yield 1 distinct txns
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.522 [INF] NTFN: New spend subscription: spend_id=6, outpoint=f7f680515d7a0e4d5eebe72c1c6bdaac751fc980147c04a5044c95922b58925a:0, script=0 463050895eb357420bf0cf419180de450489afbd895ee30165ac4925aaf1161a, height_hint=795175
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.522 [INF] NTFN: Dispatching historical spend rescan for outpoint=f7f680515d7a0e4d5eebe72c1c6bdaac751fc980147c04a5044c95922b58925a:0, script=0 463050895eb357420bf0cf419180de450489afbd895ee30165ac4925aaf1161a, start=795175, end=795175
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.522 [INF] CNCT: ChannelArbitrator(36d16d37800ff72b288d6eeaf9849633d2c2cd4514e6ab03e4dcf40e830b5da7:0): trigger userTrigger moving from state StateCommitmentBroadcasted to StateCommitmentBroadcasted
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.530 [INF] BTCN: Registering block subscription: id=5
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.530 [INF] PEER: Waiting for confirmation of close of ChannelPoint(36d16d37800ff72b288d6eeaf9849633d2c2cd4514e6ab03e4dcf40e830b5da7:0) with txid: faac6edd32f45fcdf30bac7c4cd1300463226f2e0cb56fcf4c741150cca0ed42
Jun 20 12:58:24 mother lnd[155267]: 2023-06-20 10:58:24.531 [INF] NTFN: New confirmation subscription: conf_id=1, txid=faac6edd32f45fcdf30bac7c4cd1300463226f2e0cb56fcf4c741150cca0ed42, num_confs=1 height_hint=795176
Jun 20 12:58:28 mother lnd[155267]: 2023-06-20 10:58:28.256 [INF] NTFN: New block: height=795176, sha=00000000000000000002bf03caefc811c28d80dca0dd2f944d1ef0fb00454da4
Jun 20 12:58:28 mother lnd[155267]: 2023-06-20 10:58:28.256 [INF] NTFN: Missed blocks, attempting to catch up
Jun 20 12:58:28 mother lnd[155267]: 2023-06-20 10:58:28.257 [ERR] NTFN: unable to get missed blocks: starting height 795177 is greater than ending height 795176
Jun 20 12:58:28 mother lnd[155267]: 2023-06-20 10:58:28.256 [INF] UTXN: Attempting to graduate height=795176: num_kids=0, num_babies=0
Jun 20 12:58:28 mother lnd[155267]: 2023-06-20 10:58:28.258 [INF] BTCN: Canceling block subscription: id=5
Jun 20 12:58:28 mother lnd[155267]: 2023-06-20 10:58:28.259 [INF] NTFN: Missed blocks, attempting to catch up
Jun 20 12:58:28 mother lnd[155267]: 2023-06-20 10:58:28.259 [ERR] NTFN: unable to get missed blocks: starting height 795177 is greater than ending height 795176
Jun 20 12:58:28 mother lnd[155267]: 2023-06-20 10:58:28.259 [INF] BTCN: Registering block subscription: id=6
Jun 20 12:58:33 mother lnd[155267]: 2023-06-20 10:58:33.305 [INF] RPCS: elapsed time for diameter (13) calculation: 778.940617ms
Jun 20 12:58:54 mother lnd[155267]: 2023-06-20 10:58:54.523 [WRN] LNWL: Web API does not have a fee rate for target=144, using the fee rate for target=26 instead
Jun 20 12:58:54 mother lnd[155267]: 2023-06-20 10:58:54.523 [WRN] LNWL: Web API does not have a fee rate for target=144, using the fee rate for target=26 instead
Jun 20 12:58:54 mother lnd[155267]: 2023-06-20 10:58:54.524 [INF] SWPR: Candidate sweep set of size=1 (+1 wallet inputs), has yield=-0.00001829 BTC, weight=677
Jun 20 12:58:54 mother lnd[155267]: 2023-06-20 10:58:54.568 [INF] SWPR: Creating sweep transaction affd35c27af576a6dc0287249c62c85b803aaa19cf8a5f56e6707651ff567a5b for 2 inputs (faac6edd32f45fcdf30bac7c4cd1300463226f2e0cb56fcf4c741150cca0ed42:0 (CommitmentAnchor), 66be7cc5d6f32fcb321643a5322e81d5ef2e3d2cf46bad23ca5eb313aba6766d:0 (TaprootPubKeySpend)) using 2772 sat/kw, tx_weight=725, tx_fee=0.00002292 BTC, parents_count=1, parents_fee=0.00002811 BTC, parents_weight=1116
Jun 20 12:58:54 mother lnd[155267]: 2023-06-20 10:58:54.571 [INF] LNWL: Inserting unconfirmed transaction affd35c27af576a6dc0287249c62c85b803aaa19cf8a5f56e6707651ff567a5b
Jun 20 12:58:59 mother lnd[155267]: 2023-06-20 10:58:59.579 [INF] SWPR: Candidate sweep set of size=1 (+1 wallet inputs), has yield=-0.00001829 BTC, weight=677
Jun 20 12:58:59 mother lnd[155267]: 2023-06-20 10:58:59.625 [INF] SWPR: Creating sweep transaction 925fc081a33fed20e48a972b65f86b9379602b57241a364f1874ce9184fb936e for 2 inputs (f7f680515d7a0e4d5eebe72c1c6bdaac751fc980147c04a5044c95922b58925a:0 (CommitmentAnchor), 7d2f52f140139ff23d258e28c1401b8975925e271b7028b9e4fed81ae04e1c14:0 (TaprootPubKeySpend)) using 2772 sat/kw, tx_weight=725, tx_fee=0.00002292 BTC, parents_count=1, parents_fee=0.00002811 BTC, parents_weight=1116
Jun 20 12:58:59 mother lnd[155267]: 2023-06-20 10:58:59.629 [INF] LNWL: Inserting unconfirmed transaction 925fc081a33fed20e48a972b65f86b9379602b57241a364f1874ce9184fb936e
[...]
```

`closedchannels` output about this channel:
```
"channel_point": "36d16d37800ff72b288d6eeaf9849633d2c2cd4514e6ab03e4dcf40e830b5da7:0",
"chan_id": "851512382207885312",
"chain_hash": "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
"closing_tx_hash": "faac6edd32f45fcdf30bac7c4cd1300463226f2e0cb56fcf4c741150cca0ed42",
"remote_pubkey": "02f82a2c88e4f34d3eb953daca5972922bc71ce694649764fbf2e31c28d8d54919",
"capacity": "1000000",
"close_height": 795528,
"settled_balance": "896469",
"time_locked_balance": "896469",
"close_type": "LOCAL_FORCE_CLOSE",
"open_initiator": "INITIATOR_LOCAL",
"close_initiator": "INITIATOR_LOCAL",
"resolutions": [
    {
        "resolution_type": "ANCHOR",
        "outcome": "CLAIMED",
        "outpoint": {
            "txid_bytes": "42eda0cc5011744ccf6fb50c2e6f22630430d14c7cac0bf3cd5ff432dd6eacfa",
            "txid_str": "faac6edd32f45fcdf30bac7c4cd1300463226f2e0cb56fcf4c741150cca0ed42",
            "output_index": 0
        },
        "amount_sat": "330",
        "sweep_txid": "affd35c27af576a6dc0287249c62c85b803aaa19cf8a5f56e6707651ff567a5b"
    },
    {
        "resolution_type": "COMMIT",
        "outcome": "CLAIMED",
        "outpoint": {
            "txid_bytes": "42eda0cc5011744ccf6fb50c2e6f22630430d14c7cac0bf3cd5ff432dd6eacfa",
            "txid_str": "faac6edd32f45fcdf30bac7c4cd1300463226f2e0cb56fcf4c741150cca0ed42",
            "output_index": 3
        },
        "amount_sat": "896469",
        "sweep_txid": "bf25c44a3d1e6ea50367a62a3d1abe340c8ea3dd66d99888e53ea3782711d42e"
    }
],
"alias_scids": [
],
"zero_conf_confirmed_scid": "0"
```

Seems like funds are successfully recovered. I have no idea what was the point to create this sweep txn and how to get rid of it.

LND version: v0.16.3-beta
Backend is neutrino (not mine)
Linux mother 6.2.15-200.fc37.aarch64 #1 SMP PREEMPT_DYNAMIC Thu May 11 16:16:39 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

**Comment by ziggie1984** [comment]
So I think what happened in your case when a channel is force-closed the lnd-engine will try to sweep your anchor of both commitment transaction (Local and Remote) when using a normal backend one of them will be rejected because their will only be 1 Commitment Transaction in your mempool so the other sweep will be rejected and finally not proposed to the mempool after some failed trails. In your case tho you are using the neutrino backend which has no mempool at all and it seems like the peers were accepting both sweeping transaction. 

Will test it locally if I have some spare time.

Normally your situation should be fixed by a restart because then this other transaction will not be proposed to the mempool anymore because the commitment is already confirmed. Did you try that?

**Comment by rpallai** [comment]
I tried to restart but it didn't fix anything;

`listsweeps` still lists txn 925fc081a33fed20e48a972b65f86b9379602b57241a364f1874ce9184fb936e and `walletbalance` shows 996223 sats as unconfirmed_balance.

**Comment by ziggie1984** [comment]
Ok tested with a neutrino backend and could reproduce, let me check if I can find a quick fix. Problem is, that it is blocking one of your utxos so this is definitely unintentional behaviour.

**Comment by ziggie1984** [comment]
Will come up with a fix today for this issue.

**Comment by aplnx** [comment]
Hello dear friends,

I read through this post and I can say that this is also my case. I could successfully recover my funds, but it shows an unconfirmed balance on lncli.

I have noticed that LND is having difficulty estimating fees according to the following error messages:
```
2023-08-23 11:12:53.965 [INF] SWPR: Creating sweep transaction 256...da70 for 2 inputs (2e55...cc1781d:0 (CommitmentAnchor), 29e9...c271:0 (TaprootPubKeySpend)) using 253 sat/kw, tx_weight=725, tx_fee=0.00000183 BTC, parents_count=0, parents_fee=0 BTC, parents_weight=0
2023-08-23 11:12:53.969 [ERR] BTCN: Broadcast attempt failed: -26: mempool min fee not met, 183 < 939
2023-08-23 11:12:53.970 [INF] LNWL: Inserting unconfirmed transaction 256a...da70
2023-08-23 11:12:53.977 [INF] LNWL: 256a...da70: broadcast failed because of: unmatched backend error: -26: mempool min fee not met, 183 < 939
2023-08-23 11:12:53.979 [INF] LNWL: Removed invalid transaction: (*wire.MsgTx)(0xc00d3d0bc0)({
``` 

On my node I have a bitcoind running and I can assume that fee estimation is okay. My current LND version is 0.16.2-beta. 

Please, if you can point me I can bring more information to help figure out what is the problem.

**Comment by ziggie1984** [comment]
> Please, if you can point me I can bring more information to help figure out what is the problem.

That's not related to this bug, lnd does the right fee estimation, but anchors are only profitable to sweep up to 1.8 sat/vbyte, lnd will sweep them with the min_relay fee (probably 1sat/vbyte) in your case.

Relates to #7939 

Preliminary fix which would solve your problem: just increase your min-relay fee of your bitcoin node to 2000 sats/kvb, and restart your lnd node, those sweeps should go away then until the major fix as linked in the PR is production ready

**Comment by aplnx** [comment]
> > Please, if you can point me I can bring more information to help figure out what is the problem.
> 
> That's not related to this bug, lnd does the right fee estimation, but anchors are only profitable to sweep up to 1.8 sat/vbyte, lnd will sweep them with the min_relay fee (probably 1sat/vbyte) in your case.
> 
> Relates to #7939
> 
> Preliminary fix which would solve your problem: just increase your min-relay fee of your bitcoin node to 2000 sats/kvb, and restart your lnd node, those sweeps should go away then until the major fix as linked in the PR is production ready

Do I just need to put 'sweeper.notrecoveranchoroutputs=true' on my lnd.conf?

By the way, It fails when I try to open a new channel using available on-chain funds, so it seems my funds are actually locked. This is my listunspent entry that has 0 confirmations:
```
		{
			"address_type": 4,
			"address": "bc1pa.....nf8",
			"amount_sat": 2996278,
			"pk_script": "5120.....f3b",
			"outpoint": "256a.....da70:0",
			"confirmations": 0
		},
```

**Comment by ziggie1984** [comment]
> '--sweeper.notrecoveranchoroutputs=true' is not on the help of my lnd binary. Also, It also doesn't accept this configuration when I call it from command line.

This is still a draft PR and not part of the LND suite you are running. 

> By the way, It fails when I try to open a new channel using available on-chain funds, so it seems my funds are actually locked. This is my listunspent entry that has 0 confirmations:

you were tyring with --min_conf=0 ?

**Comment by aplnx** [comment]
> > '--sweeper.notrecoveranchoroutputs=true' is not on the help of my lnd binary. Also, It also doesn't accept this configuration when I call it from command line.
> 
> This is still a draft PR and not part of the LND suite you are running.
> 
> > By the way, It fails when I try to open a new channel using available on-chain funds, so it seems my funds are actually locked. This is my listunspent entry that has 0 confirmations:
> 
> you were tyring with --min_conf=0 ?

I didn't used option --min_conf=0. I used lncli command line as usual to open a channel. It responded with unsuficient balance error message.

By the way, here follows more information on the forced close channel that led to this state:
```
{
            "channel_point": "255452f2b2c234347b9924e0df4a0c4bbf43320c331b595b76c5ebc06a903935:1",
            "chan_id": "880695619818618881",
            "chain_hash": "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
            "closing_tx_hash": "2e55e767d00413ff657433cadeee25dcefc8d8b8fe74a6a846aef9e99cc1781d",
            "remote_pubkey": "03c85808210bc3ccd048f51673a1ec90e4c0f89ec0b268c7a07ee3b00babab5076",
            "capacity": "3000000",
            "close_height": 803726,
            "settled_balance": "2996991",
            "time_locked_balance": "2996991",
            "close_type": "LOCAL_FORCE_CLOSE",
            "open_initiator": "INITIATOR_LOCAL",
            "close_initiator": "INITIATOR_LOCAL",
            "resolutions": [
                {
                    "resolution_type": "COMMIT",
                    "outcome": "CLAIMED",
                    "outpoint": {
                        "txid_bytes": "1d78c...552e",
                        "txid_str": "2e55e...781d",
                        "output_index": 1
                    },
                    "amount_sat": "2996991",
                    "sweep_txid": "29e9d9a7d55b0ac9d48f9e3af51a4bc5bdbdc5771baf11d0c62a275295b0c271"
                }
            ],
            "alias_scids": [
            ],
            "zero_conf_confirmed_scid": "0"
        }
```
There is no pending channel information. Seems everything is normal. When I restart LND it doesn't even mention anything about dealing with the unconfirmed balance. It also doesn't try to broadcast any transaction. Following, there is the walletbalance output:
```
{
    "total_balance": "4...9",
    "confirmed_balance": "1...1",
    "unconfirmed_balance": "2...8",
    "locked_balance": "0",
    "reserved_balance_anchor_chan": "100000",
    "account_balance": {
        "default": {
            "confirmed_balance": "1...1",
            "unconfirmed_balance": "2...8"
        }
    }
}
```

**Comment by aplnx** [comment]
> > '--sweeper.notrecoveranchoroutputs=true' is not on the help of my lnd binary. Also, It also doesn't accept this configuration when I call it from command line.
> 
> This is still a draft PR and not part of the LND suite you are running.
> 
> > By the way, It fails when I try to open a new channel using available on-chain funds, so it seems my funds are actually locked. This is my listunspent entry that has 0 confirmations:
> 
> you were tyring with --min_conf=0 ?

I did configured my bitcoind backend to have min_relay fee of 2000 sats/kvb and restart my lnd node. I notice that now at least is trying to publish the tx. But, it still insists to give very low min fee relay. Can I set it anywhere else?
```
2023-09-01 10:46:03.684 [INF] LNWL: Done catching up block hashes
2023-09-01 10:46:03.684 [INF] LNWL: Finished rescan for 142 addresses (synced to block 0000000000000000000349ee5c2f5644cf8301b08713256d0fa5dcbfbeda1fc3, height 805732)
2023-09-01 10:46:03.768 [INF] LNWL: 256a...da70: broadcast failed because of: unmatched backend error: -26: min relay fee not met, 183 < 362
2023-09-01 10:46:03.771 [INF] LNWL: Removed invalid transaction: (*wire.MsgTx)(0xc00267b440)({
```

**Comment by guggero** [comment]
You can also increase your mempool size to 1GB (`maxmempool=1024`).

**Comment by aplnx** [comment]
Well, I just followed the recommendation given by Ziggie which was to update my lnd version. The current version is v0.17.0-beta RC2. Everything is fine and the balance is correct!

Thanks everybody for the support!

**Comment by aplnx** [comment]
> You can also increase your mempool size to 1GB (`maxmempool=1024`).

Is this to avoid my bitcoind backend purging transactions?
