### ISSUE TITLE
[bug]: unable to start peer +  Gossip syncer for peer not found

### ISSUE THREAD

**Issue by zapomatic** [lightningnetwork/lnd#8481]
### Background

After a reboot, two (out of 95) of my peers were unable to reconnect. My node continues to attempt reconnect and gets:

```
2024-02-14 20:45:57.213 [INF] SRVR: Finalizing connection to 03080b61a2dab8ef6bd9a227377b59b43f22662430236c0c620f405dc8d422e2db@187.180.58.25:9735, inbound=false
2024-02-14 20:45:57.215 [WRN] RPCS: Gossip syncer for peer=03080b61a2dab8ef6bd9a227377b59b43f22662430236c0c620f405dc8d422e2db not found
2024-02-14 20:45:57.321 [WRN] RPCS: Gossip syncer for peer=03080b61a2dab8ef6bd9a227377b59b43f22662430236c0c620f405dc8d422e2db not found
2024-02-14 20:45:57.452 [INF] PEER: Peer(03080b61a2dab8ef6bd9a227377b59b43f22662430236c0c620f405dc8d422e2db): disconnecting 03080b61a2dab8ef6bd9a227377b59b43f22662430236c0c620f405dc8d422e2db@187.180.58.25:9735, reason: unable to start peer: unable to read init msg: read next header: read tcp 10.9.9.9:35998->187.180.58.25:9735: read: connection reset by peer
2024-02-14 20:45:57.470 [ERR] RPCS: [/lnrpc.Lightning/SendCustomMessage]: peer 03080b61a2dab8ef6bd9a227377b59b43f22662430236c0c620f405dc8d422e2db disconnected
```
One of my partner nodes sees this:
```
2024-02-14 22:54:57.042 [WRN] RPCS: Gossip syncer for peer=026d0169e8c220d8e789de1e7543f84b9041bbb3e819ab14b9824d37caa94f1eb2 not found
2024-02-14 23:05:05.208 [INF] SRVR: Disconnecting from 026d0169e8c220d8e789de1e7543f84b9041bbb3e819ab14b9824d37caa94f1eb2@5.78.104.214:38297
```

We have both tried lncli disconnect and lncli connect to re-establish, but the same resulting logs appear.

### Your environment

We are both running the same versions and environment

* version of `lnd` - `LND 0.17.3-beta`
* which operating system (`uname -a` on *Nix) - `Linux umbrel 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend  - `Bitcoin Core 26.0.0`

**Comment by ViktorTigerstrom** [comment]
Hi @zapomatic, thanks for the issue report!

> We are both running the same versions and environment

Just wanted to reverify, both you and the peer is running LND `v0.17.3-beta`, correct? We recently have had a very similar issue (https://github.com/lightningnetwork/lnd/issues/8384) when the peer was running an earlier version of LND, resulting in a similar behaviour to what you're describing. This was resolved by the peer upgrading their LND node version.

**Comment by zapomatic** [comment]
confirmed. The issue persisted after my peer restarted LND, but resolved after he did a full system reboot.

**Comment by ellemouton** [comment]
ok so are you ok with us closing this issue then @zapomatic ?

**Comment by zapomatic** [comment]
yeah, let's chalk this up to system network issue for now.
